import 'dart:convert';
import 'dart:io';

const String _out = 'lib/rendering/webgl/generated_shaders.dart';
const String _dir = 'shaders/rendering';
const String _manifestPath = '$_dir/manifest.json';

const String _header = '''
// GENERATED by tools/renderer/shaders.dart from shaders/rendering/**/*.vert,frag — do not edit.




''';

Map<String, String> _readManifest() {
  final file = File(_manifestPath);
  if (!file.existsSync()) {
    stderr.writeln('missing manifest: $_manifestPath');
    exit(1);
  }
  final decoded = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final shaders = decoded['shaders'] as Map<String, dynamic>;
  return shaders.map((key, value) => MapEntry(key, value as String));
}

String _render(Map<String, String> shaders) {
  final b = StringBuffer(_header);
  var first = true;
  for (final e in shaders.entries) {
    final f = File('$_dir/${e.key}');
    if (!f.existsSync()) {
      stderr.writeln('missing shader source: ${f.path}');
      exit(1);
    }
    var body = f.readAsStringSync().replaceAll('\r\n', '\n');
    if (!body.endsWith('\n')) body += '\n';
    if (body.contains("'''")) {
      stderr.writeln(
        "${f.path} contains a triple quote, which cannot be embedded",
      );
      exit(1);
    }
    body = body.replaceAll(r'\', r'\\').replaceAll(r'$', r'\$');
    if (!first) b.write('\n');
    first = false;
    b.write("const String ${e.value} = '''\n$body''';\n");
  }
  return b.toString();
}

void main(List<String> args) {
  final shaders = _readManifest();
  final text = _render(shaders);
  final out = File(_out);
  final current = out.existsSync()
      ? out.readAsStringSync().replaceAll('\r\n', '\n')
      : '';
  if (args.contains('--check')) {
    if (current == text) {
      stdout.writeln('generated_shaders.dart is up to date with $_dir/');
      return;
    }
    stderr.writeln(
      '$_out is STALE relative to $_dir/ — run: dart run tools/renderer/shaders.dart',
    );
    exit(1);
  }
  if (current == text) {
    stdout.writeln(
      'generated_shaders.dart already up to date (${shaders.length} shaders)',
    );
    return;
  }
  out.writeAsStringSync(text);
  stdout.writeln('wrote $_out from ${shaders.length} files in $_dir/');
}
