// GENERATED by tools/renderer/shaders.dart from shaders/rendering/**/*.vert,frag — do not edit.




const String safeWorldVertSrc = '''
#version 300 es
layout(location=0) in vec3 aPosition;
layout(location=1) in vec3 aNormal;
layout(location=2) in vec4 aColor;
layout(location=3) in float aAlpha;
layout(location=4) in vec3 aUvMat;
uniform mat4 uViewProjection;
uniform mat4 uModel;
uniform mat4 uNormalMatrix;
uniform mat4 uInstanceModels[16];
uniform mat4 uInstanceNormalMatrices[16];
uniform float uUseInstances;
out vec4 vColor;
out vec3 vNormal;
void main(){
  mat4 model=uModel;
  mat4 normalMatrix=uNormalMatrix;
  if(uUseInstances>0.5){model=uInstanceModels[gl_InstanceID];normalMatrix=uInstanceNormalMatrices[gl_InstanceID];}
  vColor=vec4(aColor.rgb,aAlpha);
  vNormal=mat3(normalMatrix)*aNormal;
  gl_Position=uViewProjection*model*vec4(aPosition,1.0);
}
''';

const String safeWorldFragSrc = '''
#version 300 es
precision highp float;
in vec4 vColor;
in vec3 vNormal;
uniform vec3 uLightDir;
uniform vec3 uAmbientColor;
uniform float uAmbientIntensity;
uniform float uAmbientLightScale;
uniform float uDirectLightScale;
out vec4 oColor;
void main(){
  vec3 n=normalize(vNormal);
  float ndotl=max(dot(n,normalize(uLightDir)),0.0);
  vec3 lit=vColor.rgb*clamp(uAmbientColor*uAmbientIntensity*uAmbientLightScale+
    vec3(ndotl)*uDirectLightScale,0.0,1.0);
  oColor=vec4(lit,vColor.a);
}
''';

const String texturedWorldVertSrc = '''
#version 300 es
layout(location=0) in vec3 aPosition;
layout(location=1) in vec3 aNormal;
layout(location=2) in vec4 aColor;
layout(location=3) in float aAlpha;
layout(location=4) in vec3 aUvMat;
uniform mat4 uViewProjection;
uniform mat4 uModel;
uniform mat4 uNormalMatrix;
uniform mat4 uInstanceModels[16];
uniform mat4 uInstanceNormalMatrices[16];
uniform float uUseInstances;
out vec4 vColor;
out vec3 vNormal;
out vec2 vUv;
void main(){
  mat4 model=uModel;
  mat4 normalMatrix=uNormalMatrix;
  if(uUseInstances>0.5){model=uInstanceModels[gl_InstanceID];normalMatrix=uInstanceNormalMatrices[gl_InstanceID];}
  vColor=vec4(aColor.rgb,aAlpha);
  vNormal=mat3(normalMatrix)*aNormal;
  vUv=aUvMat.xy;
  gl_Position=uViewProjection*model*vec4(aPosition,1.0);
}
''';

const String texturedWorldFragSrc = '''
#version 300 es
precision highp float;
in vec4 vColor;
in vec3 vNormal;
in vec2 vUv;
uniform sampler2D uAlbedo;
uniform vec3 uLightDir;
uniform vec3 uAmbientColor;
uniform float uAmbientIntensity;
uniform float uAmbientLightScale;
uniform float uDirectLightScale;
out vec4 oColor;
void main(){
  vec3 n=normalize(vNormal);
  float ndotl=max(dot(n,normalize(uLightDir)),0.0);
  vec4 tex=texture(uAlbedo,vUv);
  vec3 lit=vColor.rgb*tex.rgb*clamp(uAmbientColor*uAmbientIntensity*uAmbientLightScale+
    vec3(ndotl)*uDirectLightScale,0.0,1.0);
  oColor=vec4(lit,vColor.a*tex.a);
}
''';

const String shadowCasterVertSrc = '''
#version 300 es
layout(location=0) in vec3 aPosition;
layout(location=4) in vec3 aUvMat;
uniform mat4 uLightViewProjection;
uniform mat4 uModel;
uniform mat4 uInstanceModels[16];
uniform float uUseInstances;
out highp vec2 vUv;
// No affine premultiply here, unlike depth_prepass.vert. Affine sampling is
// an artifact of *this camera's* screen-space rasterization; the shadow map
// rasterizes the same triangle from the light, where the equivalent warp
// would be a different, unrelated distortion. A masked surface therefore
// cuts its shadow from the perspective-correct UVs — the geometrically
// right holes — while the camera passes cut theirs from whatever the PS1
// profile asked for. That divergence is deliberate: the two rasterizations
// have no shared screen space to agree in.
void main(){
  mat4 model=uModel;
  if(uUseInstances>0.5){model=uInstanceModels[gl_InstanceID];}
  vUv=aUvMat.xy;
  gl_Position=uLightViewProjection*model*vec4(aPosition,1.0);
}
''';

const String shadowCasterFragSrc = '''
#version 300 es
precision highp float;
in highp vec2 vUv;
uniform sampler2D uAlbedo;
uniform float uAlphaCutoff;
// §6.2: "alpha-masked geometry participates in shadow, prepass, and opaque
// depth-writing routes." Without this discard a lattice, a leaf or a grille
// casts the solid shadow of its bounding quad — the single most obvious way
// a masked material reads as fake. uAlphaCutoff==0 skips the fetch, so
// every opaque caster costs exactly what it did before this existed.
void main(){
  if(uAlphaCutoff>0.&&texture(uAlbedo,vUv).a<uAlphaCutoff)discard;
}
''';

const String shadowedWorldVertSrc = '''
#version 300 es
layout(location=0) in vec3 aPosition;
layout(location=1) in vec3 aNormal;
layout(location=2) in vec4 aColor;
layout(location=3) in float aAlpha;
layout(location=4) in vec3 aUvMat;
layout(location=5) in vec4 aTangent;
layout(location=6) in vec2 aUv1;
uniform mat4 uViewProjection;
uniform mat4 uView;
uniform mat4 uModel;
uniform mat4 uNormalMatrix;
uniform mat4 uInstanceModels[16];
uniform mat4 uInstanceNormalMatrices[16];
uniform float uUseInstances;
uniform mat4 uLightViewProjection;
uniform float uVertexSnapGrid;
uniform float uAffineWarpStrength;
out vec4 vColor;
out vec3 vNormal;
out highp vec2 vUv;
out highp float vUvW;
out highp vec2 vUv1;
out vec4 vLightSpacePos;
out vec3 vWorldPos;
out vec4 vTangent;
out float vViewDepth;
void main(){
  mat4 model=uModel;
  mat4 normalMatrix=uNormalMatrix;
  if(uUseInstances>0.5){model=uInstanceModels[gl_InstanceID];normalMatrix=uInstanceNormalMatrices[gl_InstanceID];}
  vColor=vec4(aColor.rgb,aAlpha);
  vNormal=mat3(normalMatrix)*aNormal;
  vec4 worldPos=model*vec4(aPosition,1.0);
  vWorldPos=worldPos.xyz;
  vTangent=vec4(mat3(normalMatrix)*aTangent.xyz,aTangent.w);
  vLightSpacePos=uLightViewProjection*worldPos;
  // RV-09 rung 5's fog: the same "linear view depth" convention SSAO/DOF
  // already reconstruct from a depth texture, computed directly here
  // instead — this pass rasterizes the actual geometry, so there is a true
  // view-space Z per-vertex already, with no texture round-trip needed.
  vViewDepth=-(uView*worldPos).z;
  vec4 clip=uViewProjection*worldPos;
  // RV-09 rung 3's PS1 profile: snaps clip-space xy to a fixed grid before
  // the perspective divide, emulating the fixed-point vertex transform
  // precision loss that gives PS1 geometry its characteristic wobble as it
  // moves. uVertexSnapGrid==0 skips the branch entirely, so the default/
  // safe path is bit-for-bit unchanged from before this rung.
  if(uVertexSnapGrid>0.0){
    vec2 ndc=clip.xy/clip.w;
    ndc=floor(ndc/uVertexSnapGrid+0.5)*uVertexSnapGrid;
    clip.xy=ndc*clip.w;
  }
  gl_Position=clip;
  // Affine UV, the PS1 rung's deferred half. GLSL ES 300 has no
  // `noperspective` qualifier, so the divide the rasterizer already performs
  // is cancelled instead of disabled: hardware hands the fragment
  // interp(v/w)/interp(1/w), so premultiplying a varying by w makes that
  // expression collapse to interp(v) — screen-space linear, which *is*
  // affine. Both varyings are scaled by the same factor so the fragment's
  // vUv/vUvW recovers exactly that, and the intermediate blend between the
  // two regimes stays continuous rather than popping at any strength.
  // uAffineWarpStrength==0 gives affineW==1.0 exactly, leaving vUv equal to
  // aUvMat.xy bit-for-bit; the fragment then skips the divide entirely on
  // the same uniform, so the perspective-correct path is untouched rather
  // than merely round-tripped. Snapping above only rewrites clip.xy, never
  // clip.w, so the two PS1 halves are independent.
  float affineW=mix(1.0,clip.w,uAffineWarpStrength);
  vUv=aUvMat.xy*affineW;
  vUvW=affineW;
  vUv1=aUv1;
}
''';

const String shadowedWorldFragSrc = '''
#version 300 es
precision highp float;
in vec4 vColor;
in vec3 vNormal;
in highp vec2 vUv;
in highp float vUvW;
in highp vec2 vUv1;
in vec4 vLightSpacePos;
in vec3 vWorldPos;
in vec4 vTangent;
in float vViewDepth;
uniform sampler2D uAlbedo;
uniform sampler2D uNormalMap;
uniform sampler2D uOrmMap;
uniform sampler2D uEmissiveMap;
uniform sampler2D uLightmap;
uniform sampler2D uShadowMap;
uniform vec3 uCameraPosition;
uniform vec3 uLightPosition;
uniform vec3 uLightDirection;
uniform vec3 uLightColor;
uniform float uLightIntensity;
uniform float uLightRange;
uniform float uLightInnerCos;
uniform float uLightOuterCos;
uniform float uSpotEnabled;
uniform vec3 uDirectionalDirection;
uniform vec3 uDirectionalColor;
uniform float uDirectionalIntensity;
uniform vec3 uPointPosition0;
uniform vec3 uPointColor0;
uniform float uPointIntensity0;
uniform float uPointRadius0;
uniform vec3 uPointPosition1;
uniform vec3 uPointColor1;
uniform float uPointIntensity1;
uniform float uPointRadius1;
uniform vec3 uPointPosition2;
uniform vec3 uPointColor2;
uniform float uPointIntensity2;
uniform float uPointRadius2;
uniform vec3 uPointPosition3;
uniform vec3 uPointColor3;
uniform float uPointIntensity3;
uniform float uPointRadius3;
uniform vec3 uDirectSpotPosition0;
uniform vec3 uDirectSpotDirection0;
uniform vec3 uDirectSpotColor0;
uniform float uDirectSpotIntensity0;
uniform float uDirectSpotRange0;
uniform float uDirectSpotInnerCos0;
uniform float uDirectSpotOuterCos0;
uniform float uDirectSpotEnabled0;
uniform vec3 uDirectSpotPosition1;
uniform vec3 uDirectSpotDirection1;
uniform vec3 uDirectSpotColor1;
uniform float uDirectSpotIntensity1;
uniform float uDirectSpotRange1;
uniform float uDirectSpotInnerCos1;
uniform float uDirectSpotOuterCos1;
uniform float uDirectSpotEnabled1;
uniform vec3 uDirectSpotPosition2;
uniform vec3 uDirectSpotDirection2;
uniform vec3 uDirectSpotColor2;
uniform float uDirectSpotIntensity2;
uniform float uDirectSpotRange2;
uniform float uDirectSpotInnerCos2;
uniform float uDirectSpotOuterCos2;
uniform float uDirectSpotEnabled2;
uniform vec3 uAmbientColor;
uniform float uAmbientIntensity;
uniform float uAmbientLightScale;
uniform float uDirectLightScale;
uniform vec3 uReflectionColor;
uniform float uReflectionIntensity;
uniform float uReflectionConfidence;
uniform vec2 uShadowMapTexelSize;
uniform float uShadowFilterRadius;
uniform float uShadowBias;
uniform vec3 uMaterialTint;
uniform vec4 uUvScaleOffset;
uniform sampler2D uSsao;
uniform vec2 uSceneColorSize;
uniform float uEmissiveStrength;
uniform float uNormalStrength;
uniform float uRoughness;
uniform float uMetallic;
uniform float uSpecularScale;
uniform float uOcclusionStrength;
uniform float uClearcoatStrength;
uniform float uClearcoatRoughness;
uniform float uLightmapIntensity;
uniform float uAffineWarpStrength;
uniform float uAlphaCutoff;
uniform float uOpaqueCoverage;
uniform vec3 uFogColor;
uniform float uFogStart;
uniform float uFogEnd;
uniform float uFogHeightFalloff;
uniform float uFogDensity;
uniform float uReceivesShadow;
uniform float uRainWetness;
uniform float uSurfaceSnowCoverage;
uniform float uSurfaceDissolution;
uniform float uThermalSourceCount;
uniform vec3 uThermalSourcePosition0;
uniform float uThermalSourceRadius0;
uniform float uThermalSourceDissolution0;
uniform vec3 uThermalSourcePosition1;
uniform float uThermalSourceRadius1;
uniform float uThermalSourceDissolution1;
uniform vec3 uThermalSourcePosition2;
uniform float uThermalSourceRadius2;
uniform float uThermalSourceDissolution2;
uniform vec3 uThermalSourcePosition3;
uniform float uThermalSourceRadius3;
uniform float uThermalSourceDissolution3;
layout(location=0)out vec4 oColor;
layout(location=1)out vec4 oGlow;

// Distance falloff (smooth to zero at uLightRange, matching SpotLight.range
// rather than an unbounded inverse-square that never reaches zero) times
// cone-edge falloff (smoothstep between the outer and inner cone angles,
  // SpotLight.outerConeRadians/innerConeRadians — both fields existed on the
  // API already but nothing read them before this, so the light previously
  // had a hard-edged, non-attenuating cone that read as flat/harsh instead of
// a graduated pool of light).
float rangeAttenuation(float dist,float range){
  float normalized=clamp(dist/max(range,.001),0.,1.);
  // Smooth quartic cutoff avoids a visible ring at the authored range while
  // retaining an inverse-square response inside the light's influence.
  float cutoff=1.-normalized*normalized*normalized*normalized;
  float inverseSquare=1./(1.+(dist*dist)/max(range*range,.001));
  return cutoff*cutoff*inverseSquare;
}

float lightAttenuation(vec3 worldPos){
  vec3 toFrag=worldPos-uLightPosition;
  float dist=length(toFrag);
  float cosAngle=dot(normalize(toFrag),normalize(uLightDirection));
  float coneFalloff=smoothstep(uLightOuterCos,uLightInnerCos,cosAngle);
  return rangeAttenuation(dist,uLightRange)*coneFalloff;
}

float pointAttenuation(vec3 worldPos,vec3 lightPosition,float lightRadius){
  float dist=length(lightPosition-worldPos);
  return rangeAttenuation(dist,lightRadius);
}

vec3 pointContribution(vec3 normal,vec3 worldPos,vec3 lightPosition,
  vec3 lightColor,float lightIntensity,float lightRadius){
  vec3 toLight=lightPosition-worldPos;
  float ndotl=max(dot(normal,normalize(toLight)),0.);
  return lightColor*lightIntensity*ndotl*
    pointAttenuation(worldPos,lightPosition,lightRadius);
}

vec3 directSpotContribution(vec3 normal,vec3 worldPos,vec3 lightPosition,
  vec3 lightDirection,vec3 lightColor,float lightIntensity,float lightRange,
  float innerCos,float outerCos,float enabled){
  vec3 toLight=lightPosition-worldPos;
  float ndotl=max(dot(normal,normalize(toLight)),0.);
  vec3 toFrag=worldPos-lightPosition;
  float cosAngle=dot(normalize(toFrag),normalize(lightDirection));
  float coneFalloff=smoothstep(outerCos,innerCos,cosAngle);
  float distanceFalloff=rangeAttenuation(length(toFrag),lightRange);
  return lightColor*lightIntensity*ndotl*coneFalloff*
    distanceFalloff*enabled;
}

// Compact Cook-Torrance response for the clean/high path. The bounded
// per-light evaluation makes roughness and metallic maps visibly useful
// without introducing a deferred light buffer.
float distributionGgx(float ndoth,float roughness){
  float a=roughness*roughness;
  float a2=a*a;
  float denom=ndoth*ndoth*(a2-1.0)+1.0;
  return a2/(3.14159265*denom*denom);
}

float geometrySchlick(float ndotv,float roughness){
  float k=(roughness+1.0)*(roughness+1.0)/8.0;
  return ndotv/(ndotv*(1.0-k)+k);
}

float geometrySmith(float ndotv,float ndotl,float roughness){
  return geometrySchlick(ndotv,roughness)*geometrySchlick(ndotl,roughness);
}

vec3 fresnelSchlick(float cosTheta,vec3 f0){
  return f0+(1.0-f0)*pow(1.0-clamp(cosTheta,0.0,1.0),5.0);
}

vec3 specularContribution(vec3 normal,vec3 viewDir,vec3 lightDir,
  vec3 lightColor,float lightIntensity,float attenuation,vec3 baseColor,
  float roughness,float metallic){
  vec3 halfDir=normalize(viewDir+lightDir);
  float ndotv=max(dot(normal,viewDir),0.0);
  float ndotl=max(dot(normal,lightDir),0.0);
  float ndoth=max(dot(normal,halfDir),0.0);
  float hdotv=max(dot(halfDir,viewDir),0.0);
  vec3 f0=mix(vec3(0.04),baseColor,metallic);
  vec3 fresnel=fresnelSchlick(hdotv,f0);
  float distribution=distributionGgx(ndoth,roughness);
  float geometry=geometrySmith(ndotv,ndotl,roughness);
  vec3 numerator=distribution*geometry*fresnel;
  float denominator=max(4.0*ndotv*ndotl,0.001);
  return numerator/denominator*lightColor*lightIntensity*attenuation*ndotl;
}

float sampleShadow(vec3 projCoord,float bias){
  float shadowDepth=texture(uShadowMap,projCoord.xy).r;
  return projCoord.z-bias>shadowDepth?0.:1.;
}

// §8.5's fog keeps the smooth distance ramp for authored horizon control, but
// the participating-medium term is an analytic optical depth along the actual
// camera-to-surface segment. For rho(y)=density*exp(-falloff*max(y,0)), the
// integral has a stable constant-height limit and therefore does not shimmer
// when a surface is nearly level with the camera. Zero density remains an
// exact no-op; the host can still use the distance ramp independently.
float heightFogOpticalDepth(vec3 rayStart,vec3 rayEnd){
  float segmentLength=length(rayEnd-rayStart);
  if(segmentLength<=0.0001||uFogDensity<=0.)return 0.;
  float falloff=max(uFogHeightFalloff,0.);
  float h0=max(rayStart.y,0.);
  float h1=max(rayEnd.y,0.);
  float integral;
  if(falloff<=0.||abs(h1-h0)<=0.0001){
    integral=segmentLength*exp(-falloff*h0);
  }else{
    float denominator=falloff*(h1-h0);
    integral=segmentLength*(exp(-falloff*h0)-exp(-falloff*h1))/denominator;
  }
  return max(uFogDensity*integral,0.);
}

float fogFactor(float viewDepth,float worldY){
  float distFactor=smoothstep(uFogStart,uFogEnd,viewDepth);
  float opticalDepth=heightFogOpticalDepth(uCameraPosition,vWorldPos);
  float mediumFactor=1.-exp(-opticalDepth);
  return clamp(max(distFactor,mediumFactor),0.,1.);
}

float shadowFactor(float ndotl){
  vec3 projCoord=vLightSpacePos.xyz/vLightSpacePos.w;
  projCoord=projCoord*.5+.5;
  if(projCoord.x<0.||projCoord.x>1.||projCoord.y<0.||projCoord.y>1.||projCoord.z>1.){
    return 1.;
  }
  // Receiver-plane style slope bias keeps grazing surfaces from acne while
  // avoiding the detached-shadow look of a large constant offset.
  float bias=max(uShadowBias*(1.-ndotl),uShadowBias*0.2666667);
  // Fixed low-discrepancy offsets avoid the directional shimmer of a regular
  // square lattice while remaining deterministic and free of per-frame noise.
  vec2 t=uShadowMapTexelSize*clamp(uShadowFilterRadius,0.,3.);
  float sum=0.;
  sum+=sampleShadow(projCoord+vec3(vec2(-.942,-.399)*t,0.),bias);
  sum+=sampleShadow(projCoord+vec3(vec2(.945,-.768)*t,0.),bias);
  sum+=sampleShadow(projCoord+vec3(vec2(-.094,.886)*t,0.),bias);
  sum+=sampleShadow(projCoord+vec3(vec2(.344,.294)*t,0.),bias);
  sum+=sampleShadow(projCoord+vec3(vec2(-.716,.642)*t,0.),bias);
  sum+=sampleShadow(projCoord+vec3(vec2(.688,-.089)*t,0.),bias);
  sum+=sampleShadow(projCoord+vec3(vec2(-.287,-.885)*t,0.),bias);
  sum+=sampleShadow(projCoord+vec3(vec2(.052,.008)*t,0.),bias);
  sum+=sampleShadow(projCoord+vec3(vec2(.831,.486)*t,0.),bias);
  return sum/9.;
}

void main(){
  // The divide that undoes the rasterizer's own perspective correction (see
  // shadowed_world.vert). Branched on the uniform rather than always
  // dividing, so a zero-strength draw samples the untouched vUv and is
  // bit-identical to the pre-affine path — the divisor is 1.0 there, but
  // only after an interpolate/divide round-trip that need not return
  // exactly 1.0. The branch is uniform across the whole draw, so it costs
  // no divergence.
  vec2 uv=uAffineWarpStrength>0.?vUv/vUvW:vUv;
  uv=uv*uUvScaleOffset.xy+uUvScaleOffset.zw;
  vec4 tex=texture(uAlbedo,uv);
  // §6.2's alpha-masked route. Deliberately the first thing after the
  // fetch it depends on, and ahead of all the lighting below: a discarded
  // fragment must not pay for four shadow-map taps and two normalizes it
  // will never use. uAlphaCutoff==0 is the pass's "this material has no
  // cutout" sentinel (MaterialDefinition.validate forbids a real zero), so
  // opaque and blended draws take a path containing no alpha compare at
  // all rather than one comparing against an unreachable threshold. The
  // same test, against the same uv, runs in depth_prepass.frag and
  // shadow_caster.frag — three passes must agree on which fragments exist
  // or SSAO, DOF and shadowing all occlude against holes this pass shaded
  // through.
  if(uAlphaCutoff>0.&&tex.a<uAlphaCutoff)discard;
  vec3 n=normalize(vNormal);
  // Surface-v2 supplies a tangent4 with OpenGL's +/-1 handedness in W.
  // Compatibility14 meshes leave the attribute at its default zero and use
  // the derivative frame below, so old content and authored tangents share
  // one shader contract.
  if(uNormalStrength>0.0){
    vec3 dp1=dFdx(vWorldPos),dp2=dFdy(vWorldPos);
    vec2 duv1=dFdx(uv),duv2=dFdy(uv);
    vec3 derivativeT=normalize(dp1*duv2.y-dp2*duv1.y);
    vec3 derivativeB=normalize(-dp1*duv2.x+dp2*duv1.x);
    vec3 authoredT=normalize(vTangent.xyz-n*dot(n,vTangent.xyz));
    bool hasAuthoredT=dot(vTangent.xyz,vTangent.xyz)>0.25;
    vec3 t=hasAuthoredT?authoredT:derivativeT;
    vec3 b=hasAuthoredT?normalize(cross(n,t)*vTangent.w):derivativeB;
    vec3 map=texture(uNormalMap,uv).xyz*2.0-1.0;
    map.xy*=uNormalStrength;
    n=normalize(mat3(t,b,n)*normalize(map));
  }
  vec3 orm=texture(uOrmMap,uv).rgb;
  float normalVariance=0.0;
  if(uNormalStrength>0.0){
    // Toksvig-style widening suppresses sub-pixel normal sparkle when a high
    // resolution map is minified. It preserves authored relief at distance
    // while converting unresolved detail into a stable roughness increase.
    vec3 normalSample=texture(uNormalMap,uv).xyz*2.0-1.0;
    vec3 normalDx=dFdx(normalSample);
    vec3 normalDy=dFdy(normalSample);
    normalVariance=dot(normalDx,normalDx)+dot(normalDy,normalDy);
  }
  float ao=texture(uSsao,gl_FragCoord.xy/uSceneColorSize).r;
  ao*=mix(1.0,orm.r,clamp(uOcclusionStrength,0.0,1.0));
  vec3 direct=vec3(0.);
  float directionalNdotL=max(dot(n,normalize(uDirectionalDirection)),0.);
  direct+=uDirectionalColor*uDirectionalIntensity*directionalNdotL;
  direct+=pointContribution(n,vWorldPos,uPointPosition0,uPointColor0,
    uPointIntensity0,uPointRadius0);
  direct+=pointContribution(n,vWorldPos,uPointPosition1,uPointColor1,
    uPointIntensity1,uPointRadius1);
  direct+=pointContribution(n,vWorldPos,uPointPosition2,uPointColor2,
    uPointIntensity2,uPointRadius2);
  direct+=pointContribution(n,vWorldPos,uPointPosition3,uPointColor3,
    uPointIntensity3,uPointRadius3);
  direct+=directSpotContribution(n,vWorldPos,uDirectSpotPosition0,
    uDirectSpotDirection0,uDirectSpotColor0,uDirectSpotIntensity0,
    uDirectSpotRange0,uDirectSpotInnerCos0,uDirectSpotOuterCos0,
    uDirectSpotEnabled0);
  direct+=directSpotContribution(n,vWorldPos,uDirectSpotPosition1,
    uDirectSpotDirection1,uDirectSpotColor1,uDirectSpotIntensity1,
    uDirectSpotRange1,uDirectSpotInnerCos1,uDirectSpotOuterCos1,
    uDirectSpotEnabled1);
  direct+=directSpotContribution(n,vWorldPos,uDirectSpotPosition2,
    uDirectSpotDirection2,uDirectSpotColor2,uDirectSpotIntensity2,
    uDirectSpotRange2,uDirectSpotInnerCos2,uDirectSpotOuterCos2,
    uDirectSpotEnabled2);
  vec3 toSpot=normalize(uLightPosition-vWorldPos);
  float spotNdotL=max(dot(n,toSpot),0.);
  float shadow=uReceivesShadow>0.5?shadowFactor(spotNdotL):1.;
  float attenuation=lightAttenuation(vWorldPos);
  direct+=uLightColor*uLightIntensity*spotNdotL*shadow*attenuation*uSpotEnabled;
  direct*=uDirectLightScale;
  // §8.5: "modulates ambient only" — SSAO must never darken the direct
  // (N.L * shadow * attenuation) term, only the ambient fill, or it would
  // double up with real shadowing and read as an incorrect global darkening
  // rather than contact occlusion specifically.
  vec3 ambient=uAmbientColor*uAmbientIntensity*uAmbientLightScale*ao;
  vec3 baseColor=vColor.rgb*tex.rgb*uMaterialTint;
  // Metallic surfaces contribute less diffuse energy; roughness keeps a
  // small, stable broadening factor until the surface-v2 camera/specular
  // block lands. Both channels therefore affect the live output rather than
  // being metadata-only fields.
  float metal=clamp(uMetallic*orm.b,0.0,1.0);
  float rough=clamp(uRoughness*orm.g,0.0,1.0);
  // Weather changes the material before direct and environment response.
  // Thawing therefore affects the same specular lobe the viewer sees,
  // instead of changing only diffuse color after the highlight is computed.
  float wetDepth=1.0-smoothstep(2.0,18.0,max(vViewDepth,0.0));
  float wetness=clamp(uRainWetness,0.0,1.0)*wetDepth;
  baseColor=mix(baseColor,baseColor*vec3(0.84,0.90,0.98),wetness*0.22);
  float upward=clamp(n.y*0.5+0.5,0.0,1.0);
  float thermalDissolution=clamp(uSurfaceDissolution,0.0,1.0);
  // A steady spherical conductive field decays approximately as 1/r. The
  // host keeps the slow latent material memory in uSurfaceDissolution; this
  // local term therefore models the spatial heat field without making warm
  // surfaces snap back or disappear at an arbitrary exponential radius.
  if(uThermalSourceCount>0.5) thermalDissolution=max(thermalDissolution,
    uThermalSourceDissolution0*clamp(uThermalSourceRadius0/
      max(distance(vWorldPos,uThermalSourcePosition0),uThermalSourceRadius0),0.,1.));
  if(uThermalSourceCount>1.5) thermalDissolution=max(thermalDissolution,
    uThermalSourceDissolution1*clamp(uThermalSourceRadius1/
      max(distance(vWorldPos,uThermalSourcePosition1),uThermalSourceRadius1),0.,1.));
  if(uThermalSourceCount>2.5) thermalDissolution=max(thermalDissolution,
    uThermalSourceDissolution2*clamp(uThermalSourceRadius2/
      max(distance(vWorldPos,uThermalSourcePosition2),uThermalSourceRadius2),0.,1.));
  if(uThermalSourceCount>3.5) thermalDissolution=max(thermalDissolution,
    uThermalSourceDissolution3*clamp(uThermalSourceRadius3/
      max(distance(vWorldPos,uThermalSourcePosition3),uThermalSourceRadius3),0.,1.));
  thermalDissolution=clamp(thermalDissolution,0.0,1.0);
  float snowCoverage=clamp(uSurfaceSnowCoverage,0.0,1.0)*
    smoothstep(0.18,0.82,upward)*(1.0-thermalDissolution*0.72);
  baseColor=mix(baseColor,vec3(0.78,0.86,0.95),snowCoverage*0.82);
  float dissolution=thermalDissolution;
  baseColor=mix(baseColor,baseColor*vec3(0.82,0.86,0.90),dissolution*0.16);
  rough=mix(rough,max(0.06,rough*0.58),dissolution*0.72);
  // Avoid singular highlights while retaining a visibly sharp porcelain
  // response at the authored low end of the roughness range.
  float specRough=max(0.045,sqrt(rough*rough+normalVariance*0.18));
  vec3 viewDir=normalize(uCameraPosition-vWorldPos);
  vec3 specular=vec3(0.0);
  specular+=specularContribution(n,viewDir,normalize(uDirectionalDirection),
    uDirectionalColor,uDirectionalIntensity,1.0,baseColor,specRough,metal);
  specular+=specularContribution(n,viewDir,
    normalize(uPointPosition0-vWorldPos),uPointColor0,uPointIntensity0,
    pointAttenuation(vWorldPos,uPointPosition0,uPointRadius0),baseColor,
    specRough,metal);
  specular+=specularContribution(n,viewDir,
    normalize(uPointPosition1-vWorldPos),uPointColor1,uPointIntensity1,
    pointAttenuation(vWorldPos,uPointPosition1,uPointRadius1),baseColor,
    specRough,metal);
  specular+=specularContribution(n,viewDir,
    normalize(uPointPosition2-vWorldPos),uPointColor2,uPointIntensity2,
    pointAttenuation(vWorldPos,uPointPosition2,uPointRadius2),baseColor,
    specRough,metal);
  specular+=specularContribution(n,viewDir,
    normalize(uPointPosition3-vWorldPos),uPointColor3,uPointIntensity3,
    pointAttenuation(vWorldPos,uPointPosition3,uPointRadius3),baseColor,
    specRough,metal);
  specular+=specularContribution(n,viewDir,
    normalize(uLightPosition-vWorldPos),uLightColor,uLightIntensity,
    lightAttenuation(vWorldPos)*uSpotEnabled*shadow,baseColor,specRough,metal);
  specular*=uDirectLightScale*uSpecularScale;
  // Keep reflected energy available to the specular lobe. The previous
  // diffuse-first clamp clipped bright ceramic response before tone mapping,
  // producing the broad plastic patches visible in low-roughness samples.
  // This split is bounded by the material metalness and lets the final
  // composite perform the intentional HDR compression once.
  vec3 diffuseEnergy=baseColor*(1.0-metal)*
    (ambient+direct*(1.0-0.25*rough));
  vec3 lit=diffuseEnergy+specular;
  // A restrained dielectric clearcoat is intentionally separate from the
  // base roughness/metalness response. It gives porcelain a broad, stable
  // grazing highlight without turning the surface into a mirror.
  vec3 coatLight=normalize(uDirectionalDirection);
  vec3 coatHalf=normalize(viewDir+coatLight);
  float coatNdotV=max(dot(n,viewDir),0.);
  float coatNdotH=max(dot(n,coatHalf),0.);
  float coatNdotL=max(dot(n,coatLight),0.);
  float coatPower=mix(128.0,8.0,clamp(uClearcoatRoughness,0.0,1.0));
  float coatFresnel=0.04+0.96*pow(1.0-coatNdotV,5.0);
  float coat=clamp(uClearcoatStrength,0.0,1.0)*coatFresnel*
    pow(coatNdotH,coatPower)*coatNdotL*uDirectionalIntensity*
    uDirectLightScale*uSpecularScale;
  lit+=uDirectionalColor*coat;
  lit+=direct*(wetness*(0.035+0.075*(1.0-rough)));
  // Environment fallback reflections are deliberately bounded and weighted
  // by wetness/grazing angle. A real probe/history hit can raise confidence;
  // the current host fallback remains visible but never masquerades as SSR.
  float reflectionNdotV=max(dot(n,viewDir),0.0);
  float reflectionFresnel=0.04+0.96*pow(1.0-reflectionNdotV,5.0);
  float reflectionSurface=clamp(wetness+0.18*dissolution,0.0,1.0);
  float reflectionConfidence=0.20+0.80*clamp(uReflectionConfidence,0.0,1.0);
  float reflectionWeight=clamp(
    uReflectionIntensity*reflectionSurface*reflectionFresnel*
      (1.0-0.72*rough)*reflectionConfidence,
    0.0,1.0);
  lit+=uReflectionColor*reflectionWeight;
  vec3 emissive=texture(uEmissiveMap,uv).rgb*uMaterialTint*uEmissiveStrength;
  lit+=emissive;
  if(uLightmapIntensity>0.0){
    lit+=baseColor*texture(uLightmap,vUv1).rgb*uLightmapIntensity;
  }
  // Fog blends the surface's own lit color toward uFogColor only — never
  // oGlow below, which stays a declared emissive quantity independent of
  // how much atmosphere sits between the surface and the camera, matching
  // §8.7's "does not infer glow from final luma" scoping: fog is a
  // property of oColor's reflected/lit light, not of emission.
  float fog=fogFactor(vViewDepth,vWorldPos.y);
  vec3 foggedLit=mix(lit,uFogColor,fog);
  // Bug 18: vColor.a*tex.a is the correct alpha for a blended draw and the
  // wrong one for everything else. present.frag copies this channel
  // straight through to a canvas created with the default alpha:true, so an
  // opaque or masked surface that emitted a texel's own alpha would show
  // the *page* through solid geometry. Coverage, not transparency, is what
  // an opaque or masked fragment writes: whatever survived the discard
  // above is fully covering, and an opaque draw always was. uOpaqueCoverage
  // is exactly 0 or 1, so the mix is exact in both directions and the
  // blended path keeps its pre-existing expression bit-for-bit.
  float outAlpha=mix(vColor.a*tex.a,1.,uOpaqueCoverage);
  oColor=vec4(foggedLit,outAlpha);
  // §8.7: bloom reads this declared attachment directly, never inferring
  // glow from oColor's final luma — a bright-but-non-emissive lit surface
  // (e.g. the checkerboard floor under strong light) must never bloom, only
  // a material with real emissiveStrength does, independent of how the
  // surface happens to be lit this frame.
  oGlow=vec4(emissive,1.);
}
''';

const String presentVertSrc = '''
#version 300 es
out vec2 vUv;
void main(){
  vec2 p=vec2(float((gl_VertexID<<1)&2),float(gl_VertexID&2));
  vUv=p;
  gl_Position=vec4(p*2.0-1.0,0.0,1.0);
}
''';

const String presentFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uTex;
uniform float uExposure;
uniform float uVignette;
uniform float uGrain;
uniform float uOutputEncoding;
uniform float uToneMap;
out vec4 oColor;

float hash(vec2 p){
  return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);
}

vec3 reinhardToneMap(vec3 color){
  return color/(vec3(1.)+color);
}

vec3 linearToSrgb(vec3 color){
  vec3 cutoff=step(vec3(.0031308),color);
  vec3 low=color*12.92;
  vec3 high=1.055*pow(max(color,vec3(0.)),vec3(1./2.4))-.055;
  return mix(low,high,cutoff);
}

void main(){
  vec4 source=texture(uTex,vUv);
  // Exposure operates in scene-linear space; tone mapping prevents HDR
  // highlights from clipping before the selected output transfer function.
  vec3 color=max(source.rgb,vec3(0.))*max(uExposure,0.);
  color=mix(color,reinhardToneMap(color),clamp(uToneMap,0.,1.));
  float edge=distance(vUv,vec2(.5));
  float vignette=smoothstep(.35,.78,edge);
  color*=1.-clamp(uVignette,0.,1.)*vignette;
  if(uOutputEncoding>.5) color=linearToSrgb(max(color,vec3(0.)));
  // Atmospheric precipitation is submitted as depth-tested world geometry;
  // the present pass must never paint weather over unrelated surfaces.
  // A stable screen-space grain keeps captures reproducible for a fixed
  // viewport while still giving the dark gothic presentation a fine film
  // texture. It is deliberately tiny and never changes alpha.
  color+=((hash(gl_FragCoord.xy)-.5)*.06)*max(uGrain,0.);
  oColor=vec4(clamp(color,0.,1.),source.a);
}
''';

const String depthPrepassVertSrc = '''
#version 300 es
layout(location=0) in vec3 aPosition;
layout(location=4) in vec3 aUvMat;
uniform mat4 uViewProjection;
uniform mat4 uModel;
uniform mat4 uInstanceModels[16];
uniform float uUseInstances;
uniform float uVertexSnapGrid;
uniform float uAffineWarpStrength;
out highp vec2 vUv;
out highp float vUvW;
// This prepass must land geometry on exactly the same pixels shadowedWorld
// will, because its depth is what SSAO occludes against and what
// shadowedWorld then samples back at its *own* gl_FragCoord. Snapping there
// and not here would mean the AO texel a fragment reads was computed for a
// slightly different surface than the one being shaded, and the error grows
// with the grid. The snap math below is deliberately identical to
// shadowed_world.vert's, including uVertexSnapGrid==0 skipping the branch.
// The same reasoning now covers UVs: an alpha-masked surface's holes must
// land on the same pixels in both passes, and affine sampling moves where a
// given texel lands, so the w-premultiply below is the same expression
// shadowed_world.vert uses and is driven from the same per-material weight.
void main(){
  mat4 model=uModel;
  if(uUseInstances>0.5){model=uInstanceModels[gl_InstanceID];}
  vec4 clip=uViewProjection*model*vec4(aPosition,1.0);
  if(uVertexSnapGrid>0.0){
    vec2 ndc=clip.xy/clip.w;
    ndc=floor(ndc/uVertexSnapGrid+0.5)*uVertexSnapGrid;
    clip.xy=ndc*clip.w;
  }
  gl_Position=clip;
  float affineW=mix(1.0,clip.w,uAffineWarpStrength);
  vUv=aUvMat.xy*affineW;
  vUvW=affineW;
}
''';

const String depthPrepassFragSrc = '''
#version 300 es
precision highp float;
in highp vec2 vUv;
in highp float vUvW;
uniform sampler2D uAlbedo;
uniform float uAlphaCutoff;
uniform float uAffineWarpStrength;
// §6.2: "includes opaque + alpha-masked depth." A masked surface's holes
// must not write depth, or SSAO occludes against geometry the world pass
// discarded and DOF's CoC defocuses against a surface nothing shaded. The
// compare is bit-identical to shadowed_world.frag's — same uv recovery,
// same threshold, same direction — because any divergence reintroduces
// exactly the class of bug the vertex-snap parity fix (bug 17) closed.
// Everything is inside the uAlphaCutoff>0. branch, so an unmasked draw
// costs no texture fetch at all here, only the interpolation the varyings
// were already going to do.
void main(){
  if(uAlphaCutoff>0.){
    vec2 uv=uAffineWarpStrength>0.?vUv/vUvW:vUv;
    if(texture(uAlbedo,uv).a<uAlphaCutoff)discard;
  }
}
''';

const String depthDebugFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uSceneDepth;
uniform float uNear;
uniform float uFar;
uniform float uDisplayRange;
out vec4 oColor;
void main(){
  float raw=texture(uSceneDepth,vUv).r;
  float ndc=raw*2.0-1.0;
  float linear=(2.0*uNear*uFar)/(uFar+uNear-ndc*(uFar-uNear));
  // uFar is the camera's real projection far plane (100, for correct depth
  // reconstruction above) — normalizing display shade against it directly
  // would crush every visible surface (a handful of units away) into a
  // sliver near 0.0, indistinguishable from black, while the empty
  // background (which clears to exactly uFar) reads pure white. uDisplayRange
  // is a separate, much smaller distance chosen to match this scene's
  // actual scale, so nearby geometry spans a real visible gradient instead
  // of a hard silhouette.
  float shade=clamp(linear/uDisplayRange,0.0,1.0);
  oColor=vec4(vec3(shade),1.0);
}
''';

const String ssaoOcclusionFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uSceneDepth;
uniform float uNear;
uniform float uFar;
uniform float uProjScaleX;
uniform float uProjScaleY;
uniform float uRadius;
uniform float uStrength;
out vec4 oColor;

const int KERNEL_SIZE=8;
const vec3 KERNEL[8]=vec3[8](
  vec3( 0.35, 0.23, 0.45),
  vec3(-0.28, 0.41, 0.32),
  vec3( 0.18,-0.36, 0.55),
  vec3(-0.42,-0.19, 0.28),
  vec3( 0.51, 0.08, 0.18),
  vec3(-0.11, 0.53, 0.16),
  vec3( 0.07,-0.48, 0.38),
  vec3(-0.33,-0.31, 0.48)
);

float linearDepth(float raw){
  float ndc=raw*2.0-1.0;
  return (2.0*uNear*uFar)/(uFar+uNear-ndc*(uFar-uNear));
}

vec3 viewPosAt(vec2 uv){
  float viewZ=-linearDepth(texture(uSceneDepth,uv).r);
  vec2 ndc=uv*2.0-1.0;
  float viewX=ndc.x*(-viewZ)/uProjScaleX;
  float viewY=ndc.y*(-viewZ)/uProjScaleY;
  return vec3(viewX,viewY,viewZ);
}

// Pinned per-pixel kernel rotation — a deterministic hash of screen
// position, not per-frame randomness, matching §8.5's "rotates a small
// kernel from pinned blue noise" without the extra machinery of an actual
// noise texture: the rotation angle is stable across frames for a given
// pixel, which is what "pinned" requires (temporal stability), while still
// varying spatially enough to break up banding between neighboring samples.
float pinnedRotation(vec2 fragCoord){
  return fract(sin(dot(fragCoord,vec2(12.9898,78.233)))*43758.5453)*6.2831853;
}

void main(){
  vec3 originView=viewPosAt(vUv);
  // Screen-space derivatives reconstruct a per-fragment normal from
  // neighboring depth samples alone — no G-buffer normal attachment exists
  // (deferred; see depth_prepass.dart's doc comment), which is sufficient
  // for a chunky/stylized AO term rather than a precision-critical one.
  vec3 normalView=normalize(cross(dFdx(originView),dFdy(originView)));

  // Rotates each kernel sample's tangent-plane (x,y) offset in place, before
  // it's transformed into view space by tbn below — this is what actually
  // varies the kernel per pixel; rotating the already-reprojected screen UV
  // afterward would rotate around the wrong origin and misalign every
  // sample from the surface it's meant to test.
  float angle=pinnedRotation(gl_FragCoord.xy);
  float ca=cos(angle);
  float sa=sin(angle);
  mat2 rot=mat2(ca,sa,-sa,ca);

  vec3 up=abs(normalView.z)<0.99?vec3(0.0,0.0,1.0):vec3(1.0,0.0,0.0);
  vec3 tangent=normalize(cross(up,normalView));
  vec3 bitangent=cross(normalView,tangent);
  mat3 tbn=mat3(tangent,bitangent,normalView);

  float occlusion=0.0;
  for(int i=0;i<KERNEL_SIZE;i++){
    vec3 kernelSample=KERNEL[i];
    kernelSample.xy=rot*kernelSample.xy;
    vec3 samplePos=originView+tbn*kernelSample*uRadius;
    // Project the sample's view-space position back to screen UV using the
    // same scale factors used to reconstruct it, inverted.
    vec2 sampleUv=vec2(
      samplePos.x*uProjScaleX/(-samplePos.z),
      samplePos.y*uProjScaleY/(-samplePos.z)
    );
    // NDC [-1,1] -> UV [0,1] requires the constant 0.5, not vUv (the
    // *current* fragment's own UV) — adding vUv here was a real bug: it
    // conflated "this sample's own absolute reprojected screen position"
    // with "an offset relative to the current fragment," producing an
    // error of (vUv-0.5) per axis that grows with distance from screen
    // center. That's exactly what produced a huge, blobby, non-local dark
    // region instead of contact occlusion — every sample tested a wildly
    // wrong depth location except right at screen center, where the error
    // happened to be near zero.
    sampleUv=sampleUv*0.5+0.5;
    if(sampleUv.x<0.0||sampleUv.x>1.0||sampleUv.y<0.0||sampleUv.y>1.0){
      continue;
    }
    vec3 occluderView=viewPosAt(sampleUv);
    float rangeCheck=smoothstep(0.0,1.0,uRadius/max(abs(originView.z-occluderView.z),0.0001));
    occlusion+=(occluderView.z>=samplePos.z+0.02?1.0:0.0)*rangeCheck;
  }
  float ao=1.0-clamp((occlusion/float(KERNEL_SIZE))*uStrength,0.0,1.0);
  oColor=vec4(vec3(ao),1.0);
}
''';

const String ssaoBlurFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uSsaoRaw;
uniform sampler2D uSceneDepth;
uniform vec2 uTexelSize;
uniform float uNear;
uniform float uFar;
out vec4 oColor;

float linearDepth(float raw){
  float ndc=raw*2.0-1.0;
  return (2.0*uNear*uFar)/(uFar+uNear-ndc*(uFar-uNear));
}

// §8.5: "uses a depth-aware bilateral blur rather than smearing across
// silhouettes" — a plain box blur would bleed occlusion from a near object
// onto a far background behind it (or vice versa) whenever they share
// screen-space pixels near a silhouette edge; weighting each tap by how
// close its depth is to the center tap's depth is what keeps the blur
// confined to one surface at a time.
void main(){
  float centerDepth=linearDepth(texture(uSceneDepth,vUv).r);
  float sum=0.0;
  float weightSum=0.0;
  for(int y=-2;y<=2;y++){
    for(int x=-2;x<=2;x++){
      vec2 offset=vec2(float(x),float(y))*uTexelSize;
      vec2 sampleUv=vUv+offset;
      float sampleDepth=linearDepth(texture(uSceneDepth,sampleUv).r);
      float depthWeight=1.0/(1.0+abs(sampleDepth-centerDepth)*4.0);
      sum+=texture(uSsaoRaw,sampleUv).r*depthWeight;
      weightSum+=depthWeight;
    }
  }
  float blurred=sum/max(weightSum,0.0001);
  oColor=vec4(vec3(blurred),1.0);
}
''';

const String bloomBlurFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uSource;
uniform vec2 uTexelStep;
out vec4 oColor;

const float WEIGHTS[5]=float[5](0.227027,0.1945946,0.1216216,0.054054,0.016216);

void main(){
  vec3 sum=texture(uSource,vUv).rgb*WEIGHTS[0];
  for(int i=1;i<5;i++){
    vec2 offset=uTexelStep*float(i);
    sum+=texture(uSource,vUv+offset).rgb*WEIGHTS[i];
    sum+=texture(uSource,vUv-offset).rgb*WEIGHTS[i];
  }
  oColor=vec4(sum,1.0);
}
''';

const String bloomCompositeFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uBloom;
uniform float uBloomStrength;
out vec4 oColor;

void main(){
  oColor=vec4(texture(uBloom,vUv).rgb*uBloomStrength,1.0);
}
''';

const String dofCompositeFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uSharp;
uniform sampler2D uBlurred;
uniform sampler2D uSceneDepth;
uniform float uNear;
uniform float uFar;
uniform float uFocusDistance;
uniform float uFocusRange;
uniform float uStrength;
out vec4 oColor;

float linearDepth(float raw){
  float ndc=raw*2.0-1.0;
  return (2.0*uNear*uFar)/(uFar+uNear-ndc*(uFar-uNear));
}

// Circle-of-confusion is a simple linear ramp from the focus distance
// outward (front and back treated the same — no separate near/far falloff
// curve), clamped to [0,1] and scaled by uStrength so
// PostProcessState.depthOfFieldStrength == 0 is a true no-op (coc == 0
// everywhere, oColor == the sharp source exactly).
void main(){
  float depth=linearDepth(texture(uSceneDepth,vUv).r);
  float coc=clamp(abs(depth-uFocusDistance)/max(uFocusRange,0.0001),0.0,1.0)*uStrength;
  vec3 sharp=texture(uSharp,vUv).rgb;
  vec3 blurred=texture(uBlurred,vUv).rgb;
  oColor=vec4(mix(sharp,blurred,coc),1.0);
}
''';

const String gradeLutFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uScene;
uniform sampler2D uLut;
uniform float uLutSize;
uniform float uStrength;
out vec4 oColor;

// §5.3's "identity LUT" baseline resource and this shader's actual grade LUT
// are both just textures in this same unwrapped-3D-LUT layout (width =
// size*size, height = size, blue index selects a size*size horizontal
// slice) — there is nothing identity-specific about the sampling path
// itself, only about what a given LUT texture's texels happen to encode.
vec3 sampleLut(vec3 color){
  float size=uLutSize;
  float maxIndex=size-1.0;
  vec3 scaled=clamp(color,0.0,1.0)*maxIndex;
  float bLow=floor(scaled.b);
  float bHigh=min(bLow+1.0,maxIndex);
  float bFrac=scaled.b-bLow;
  vec2 texel=vec2(1.0/(size*size),1.0/size);
  vec2 rg=vec2(scaled.r+0.5,scaled.g+0.5);
  vec2 uvLow=vec2((bLow*size+rg.x)*texel.x,rg.y*texel.y);
  vec2 uvHigh=vec2((bHigh*size+rg.x)*texel.x,rg.y*texel.y);
  vec3 colorLow=texture(uLut,uvLow).rgb;
  vec3 colorHigh=texture(uLut,uvHigh).rgb;
  return mix(colorLow,colorHigh,bFrac);
}

void main(){
  vec3 scene=texture(uScene,vUv).rgb;
  vec3 graded=sampleLut(scene);
  oColor=vec4(mix(scene,graded,uStrength),1.0);
}
''';

const String ps1QuantizeFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uScene;
uniform float uQuantizationBits;
uniform float uDitherStrength;
out vec4 oColor;

const float BAYER4X4[16]=float[16](
  0.0,8.0,2.0,10.0,
  12.0,4.0,14.0,6.0,
  3.0,11.0,1.0,9.0,
  15.0,7.0,13.0,5.0
);

float bayerValue(vec2 fragCoord){
  int x=int(mod(fragCoord.x,4.0));
  int y=int(mod(fragCoord.y,4.0));
  return BAYER4X4[y*4+x]/16.0;
}

// §6.2's "quantization/dither is an explicit composite after LUT grade":
// an ordered (Bayer 4x4) dither offset, scaled to one quantization step, is
// added before rounding to uQuantizationBits levels per channel — this is
// what breaks a hard quantization boundary into a dithered gradient instead
// of a flat color band. uQuantizationBits==8 (RGBA8's own native precision)
// with uDitherStrength==0 round-trips the source exactly: no dither offset
// is added, and floor(x*255+0.5)/255 returns an already-8-bit value
// unchanged.
void main(){
  vec3 scene=texture(uScene,vUv).rgb;
  float levels=pow(2.0,uQuantizationBits)-1.0;
  float dither=(bayerValue(gl_FragCoord.xy)-0.5)*uDitherStrength/levels;
  vec3 dithered=clamp(scene+dither,0.0,1.0);
  vec3 quantized=floor(dithered*levels+0.5)/levels;
  oColor=vec4(quantized,1.0);
}
''';

const String vhsFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uScene;
uniform sampler2D uHistory;
uniform float uTime;
uniform float uChromaWeight;
uniform float uTrackingWeight;
uniform float uNoiseWeight;
uniform float uHeadSwitchWeight;
uniform float uDropoutWeight;
uniform float uGhostWeight;
out vec4 oColor;

float hash(vec2 p){
  return fract(sin(dot(p,vec2(12.9898,78.233)))*43758.5453);
}

// §8.10: "sample the jittered/tracking UV before YIQ/chroma work so later
// sampling does not overwrite earlier effects" — tracking jitter is
// computed and applied to the UV exactly once, up front; every later
// effect either operates on the resulting single sample or samples a
// further offset FROM that same jittered UV, never re-reading uScene at
// the original vUv.
void main(){
  float scanline=vUv.y;

  // Tracking: a per-scanline horizontal jitter, re-rolled roughly 8 times
  // a second (not per-frame) so it reads as tape wobble rather than
  // high-frequency noise. Comfort clamp: 0.02 UV (a few source texels at
  // this bootstrap's 384-wide internal resolution) is the max displacement
  // regardless of weight — a weight of 1.0 must read as "visibly glitchy,"
  // never as "the image is unreadable."
  float trackingNoise=hash(vec2(floor(scanline*216.0),floor(uTime*8.0)))-0.5;
  float jitter=trackingNoise*0.02*uTrackingWeight;
  vec2 uv=vec2(clamp(vUv.x+jitter,0.0,1.0),vUv.y);
  vec3 raw=texture(uScene,uv).rgb;

  // Chroma bleed: convert to YIQ, sample a second, further-offset UV for
  // the chroma (I/Q) channels only — luma (what reads as "sharp" to the
  // eye) stays exactly where tracking already put it; only color smears.
  vec2 chromaUv=vec2(clamp(uv.x+0.01*uChromaWeight,0.0,1.0),uv.y);
  vec3 rawChroma=texture(uScene,chromaUv).rgb;
  float y=dot(raw,vec3(0.299,0.587,0.114));
  float i=dot(rawChroma,vec3(0.596,-0.274,-0.322));
  float q=dot(rawChroma,vec3(0.211,-0.523,0.312));
  vec3 yiqColor=vec3(
    y+0.956*i+0.621*q,
    y-0.272*i-0.647*q,
    y-1.106*i+1.703*q
  );
  vec3 color=mix(raw,yiqColor,uChromaWeight);

  // Static/snow: modeled in YIQ (luma + chroma), the same conversion
  // chroma bleed already uses above, not independent RGB — real analog
  // colour noise comes from the chroma subcarrier, so its hues are
  // correlated/limited rather than arbitrary per-channel static. Noise
  // cells are quantized coarser along x than y, giving each speckle a
  // short horizontal dash instead of an isolated dot — a "vague line
  // shape," matching how scanline-based static actually streaks. A
  // sparser, stronger sparkle layer and a rare single-sample micro-
  // distortion (an actual tiny position offset, not just colour) are both
  // gated by a high-threshold mask so only occasional pixels carry the
  // effect — small magnitude on top of that sparsity, for a sprinkle, not
  // a wash.
  vec2 noiseCell=vec2(floor(gl_FragCoord.x/3.0),gl_FragCoord.y)+uTime*60.0;
  float noiseY=(hash(noiseCell)-0.5)*0.05;
  float noiseI=(hash(noiseCell+vec2(17.0,3.0))-0.5)*0.14;
  float noiseQ=(hash(noiseCell+vec2(53.0,29.0))-0.5)*0.14;
  vec3 noiseYiq=vec3(
    noiseY+0.956*noiseI+0.621*noiseQ,
    noiseY-0.272*noiseI-0.647*noiseQ,
    noiseY-1.106*noiseI+1.703*noiseQ
  );
  color+=noiseYiq*uNoiseWeight;
  float sparkleMask=step(0.995,hash(noiseCell+vec2(97.0,3.0)));
  float sparkleI=(hash(noiseCell+5.0)-0.5)*2.0;
  float sparkleQ=(hash(noiseCell+9.0)-0.5)*2.0;
  vec3 sparkleYiq=0.5+0.5*vec3(
    0.956*sparkleI+0.621*sparkleQ,
    -0.272*sparkleI-0.647*sparkleQ,
    -1.106*sparkleI+1.703*sparkleQ
  );
  color+=sparkleYiq*sparkleMask*0.3*uNoiseWeight;
  float distortMask=step(0.997,hash(noiseCell+vec2(43.0,61.0)));
  vec2 distortOffset=
    vec2(hash(noiseCell+1.0)-0.5,hash(noiseCell+2.0)-0.5)*0.01;
  vec3 distortColor=texture(uScene,clamp(uv+distortOffset,0.0,1.0)).rgb;
  color=mix(color,distortColor,distortMask*0.5*uNoiseWeight);

  // Head-switch band: a thin strip near the bottom of frame (where a real
  // VCR's playback head crosses the tape edge) gets a stronger tear,
  // fading smoothly over the band's height rather than a hard cutoff.
  float headSwitchBand=smoothstep(0.06,0.0,abs(scanline-0.98));
  float headSwitchJitter=(hash(vec2(uTime*30.0,scanline))-0.5)*0.06;
  vec2 headSwitchUv=vec2(
    clamp(uv.x+headSwitchJitter*uHeadSwitchWeight*headSwitchBand,0.0,1.0),
    uv.y
  );
  vec3 headSwitchColor=texture(uScene,headSwitchUv).rgb;
  color=mix(color,headSwitchColor,uHeadSwitchWeight*headSwitchBand);

  // Dropout: sparse, per-scanline streaks mimicking analog tape dropout.
  // Real dropout is neither a flat full-width bar nor a fixed brightness —
  // a per-x noise mask (smoothstepped, not a hard cutoff) makes each
  // streak's width and edges vary along its length, and a per-streak
  // random intensity keeps consecutive dropouts from looking identical. A
  // slow ~6Hz reroll (not per-frame) and a high activation threshold keep
  // this an occasional glitch rather than a strobe — subtle enough not to
  // distract during continuous play, even at uDropoutWeight's full value.
  float dropoutCell=floor(uTime*6.0);
  float dropoutRoll=hash(vec2(floor(scanline*216.0),dropoutCell));
  float dropoutActive=step(0.994,dropoutRoll);
  float dropoutIntensity=hash(vec2(dropoutCell,17.0))*0.5+0.4;
  float dropoutMask=hash(
    vec2(floor(uv.x*48.0),floor(scanline*216.0)+dropoutCell*3.0)
  );
  float dropoutStripe=
    dropoutActive*uDropoutWeight*smoothstep(0.3,0.9,dropoutMask);
  color=mix(color,vec3(dropoutIntensity),dropoutStripe*0.8);

  // Ghosting: blends in last frame's own VHS *output* (uHistory, never
  // uScene), horizontally offset, for a trailing double-image echo —
  // reading the previous frame's already-composited result is what makes
  // this a genuine feedback trail rather than a static double-exposure.
  vec2 ghostUv=vec2(clamp(uv.x-0.015,0.0,1.0),uv.y);
  vec3 ghostColor=texture(uHistory,ghostUv).rgb;
  color=mix(color,ghostColor,uGhostWeight*0.5);

  oColor=vec4(clamp(color,0.0,1.0),1.0);
}
''';

const String volumetricLightFragSrc = '''
#version 300 es
precision highp float;

in vec2 vUv;
layout(location = 0) out vec4 oColor;

uniform sampler2D uSceneDepth;
uniform float uNear;
uniform float uFar;
uniform mat4 uViewProjection;
uniform vec3 uLightDir;
uniform vec3 uLightColor;
uniform float uShaftIntensity;
uniform float uFogDensity;
uniform float uAnisotropy;
uniform mat4 uView;
uniform mat4 uInverseProjection;
uniform vec3 uVolumetricAlbedo;
uniform float uVolumetricHeightFalloff;
uniform float uVolumetricDustDensity;
uniform float uVolumetricJitter;
uniform float uVolumetricIntensity;
uniform float uVolumetricSampleCount;
uniform float uVolumetricSourceCount;

uniform vec3 uSourcePosition0;
uniform vec3 uSourceColor0;
uniform float uSourceIntensity0;
uniform float uSourceReferenceDistance0;
uniform float uSourceCutoffDistance0;
uniform vec3 uSourcePosition1;
uniform vec3 uSourceColor1;
uniform float uSourceIntensity1;
uniform float uSourceReferenceDistance1;
uniform float uSourceCutoffDistance1;
uniform vec3 uSourcePosition2;
uniform vec3 uSourceColor2;
uniform float uSourceIntensity2;
uniform float uSourceReferenceDistance2;
uniform float uSourceCutoffDistance2;
uniform vec3 uSourcePosition3;
uniform vec3 uSourceColor3;
uniform float uSourceIntensity3;
uniform float uSourceReferenceDistance3;
uniform float uSourceCutoffDistance3;

float linearDepth(float depth) {
  float z = depth * 2.0 - 1.0;
  return (2.0 * uNear * uFar) / max(uFar + uNear - z * (uFar - uNear), 1e-4);
}

float phaseHenyeyGreenstein(float cosTheta, float anisotropy) {
  float g = clamp(anisotropy, -0.85, 0.85);
  float denominator = 1.0 + g * g - 2.0 * g * cosTheta;
  return (1.0 - g * g) / (12.5663706 * pow(max(denominator, 1e-3), 1.5));
}

vec3 sourceContribution(
  vec3 position,
  vec3 color,
  float intensity,
  float referenceDistance,
  float cutoffDistance,
  vec3 viewRay,
  float rayLength
) {
  vec4 clip = uViewProjection * vec4(position, 1.0);
  if (clip.w <= 0.0) return vec3(0.0);
  vec3 sourceView = (uView * vec4(position, 1.0)).xyz;
  float sourceDistance = length(sourceView);
  float tClosest = clamp(dot(sourceView, viewRay), 0.0, rayLength);
  vec3 sampleToSource = sourceView - viewRay * tClosest;
  float distanceToSource = max(length(sampleToSource), 1e-3);
  float cutoff = 1.0 - smoothstep(
    cutoffDistance * 0.65, cutoffDistance, sourceDistance);
  float inverseSquare = intensity * referenceDistance * referenceDistance /
      max(distanceToSource * distanceToSource,
          referenceDistance * referenceDistance);
  // The incoming direction is source -> sample and the outgoing direction is
  // sample -> camera. This is the same phase convention as the directional
  // medium path, but now evaluated against the located source.
  float phase = phaseHenyeyGreenstein(
    dot(normalize(sampleToSource), viewRay), uAnisotropy);
  // Located practicals and lightning must also acquire visible body in a
  // dust-filled room. Use the same broad haze plus particulate density as the
  // directional march; otherwise a clear-air fog toggle would accidentally
  // erase dust-lit source rays while the directional shafts still showed it.
  float mediumDensity = max(uFogDensity + uVolumetricDustDensity, 0.0);
  float mediumWeight = 1.0 - exp(-max(
    mediumDensity * min(rayLength, cutoffDistance), 0.0));
  float pathWeight = clamp(
    rayLength / max(sourceDistance, referenceDistance), 0.0, 1.0);
  return color * inverseSquare * phase * cutoff * mediumWeight * pathWeight *
    uVolumetricIntensity * 0.35;
}

void main() {
  float depth = texture(uSceneDepth, vUv).r;
  vec4 viewPoint = uInverseProjection * vec4(vUv * 2.0 - 1.0, -1.0, 1.0);
  viewPoint /= max(abs(viewPoint.w), 1e-5);
  vec3 viewRay = normalize(viewPoint.xyz);
  // linearDepth is camera-space Z; convert it to distance along the actual
  // reconstructed ray so wide and tall projections integrate equally.
  float cameraDepth = linearDepth(depth);
  float rayLength = min(cameraDepth / max(-viewRay.z, 1e-3), uFar);
  float density = max(uFogDensity, 0.0);

  // A fixed, bounded integral keeps the pass deterministic and makes its
  // cost predictable on weak adapters. The depth buffer stops integration at
  // the first opaque surface, so shafts do not leak through geometry.
  const int maxSampleCount = 24;
  int sampleCount = int(clamp(uVolumetricSampleCount, 4.0, 24.0));
  vec3 scatter = vec3(0.0);
  float transmittance = 1.0;
  float stepLength = rayLength / float(sampleCount);
  float jitterSeed = fract(sin(dot(vUv, vec2(127.1, 311.7))) * 43758.5453);
  float jitter = (jitterSeed - 0.5) * clamp(uVolumetricJitter, 0.0, 0.5);
  for (int i = 0; i < maxSampleCount; i++) {
    if (i >= sampleCount) break;
    float distanceAlongRay = clamp(
      (float(i) + 0.5 + jitter) * stepLength, 0.0, rayLength);
    float heightWeight = exp(-max(distanceAlongRay * uVolumetricHeightFalloff, 0.0));
    // Dust is a separate, host-resolved particulate phase. It is denser near
    // the occupied room volume than the broad atmospheric haze, so shafts gain
    // visible body without turning the far horizon opaque. At zero density the
    // extra term is exactly zero and the established fog path is unchanged.
    float dustWeight = exp(-max(distanceAlongRay *
      uVolumetricHeightFalloff * 0.45, 0.0));
    float opticalDensity = density +
      max(uVolumetricDustDensity, 0.0) * dustWeight;
    float opticalDepth = opticalDensity * stepLength * heightWeight;
    float sampleTransmittance = exp(-opticalDepth);
    float phase = phaseHenyeyGreenstein(dot(normalize(-uLightDir), viewRay), uAnisotropy);
    scatter += transmittance * (uLightColor * uVolumetricAlbedo *
      uShaftIntensity * uVolumetricIntensity * phase) * opticalDepth;
    transmittance *= sampleTransmittance;
  }

  if (uVolumetricSourceCount > 0.5) {
    scatter += sourceContribution(
      uSourcePosition0, uSourceColor0, uSourceIntensity0,
      uSourceReferenceDistance0, uSourceCutoffDistance0, viewRay, rayLength);
  }
  if (uVolumetricSourceCount > 1.5) {
    scatter += sourceContribution(
      uSourcePosition1, uSourceColor1, uSourceIntensity1,
      uSourceReferenceDistance1, uSourceCutoffDistance1, viewRay, rayLength);
  }
  if (uVolumetricSourceCount > 2.5) {
    scatter += sourceContribution(
      uSourcePosition2, uSourceColor2, uSourceIntensity2,
      uSourceReferenceDistance2, uSourceCutoffDistance2, viewRay, rayLength);
  }
  if (uVolumetricSourceCount > 3.5) {
    scatter += sourceContribution(
      uSourcePosition3, uSourceColor3, uSourceIntensity3,
      uSourceReferenceDistance3, uSourceCutoffDistance3, viewRay, rayLength);
  }

  // Fade the final sample at the far plane and keep the additive output
  // bounded so a storm flash cannot blow out the entire frame.
  float farFade = 1.0 - smoothstep(uFar * 0.75, uFar, rayLength);
  oColor = vec4(min(scatter * farFade, vec3(8.0)), 1.0);
}
''';

const String volumetricCompositeFragSrc = '''
#version 300 es
precision highp float;

in vec2 vUv;
layout(location = 0) out vec4 oColor;
uniform sampler2D uVolumetric;
uniform float uVolumetricStrength;

void main() {
  vec3 light = texture(uVolumetric, vUv).rgb;
  oColor = vec4(light * max(uVolumetricStrength, 0.0), 1.0);
}
''';
