// GENERATED by tools/renderer/shaders.dart from shaders/rendering/**/*.vert,frag — do not edit.




const String safeWorldVertSrc = '''
#version 300 es
layout(location=0) in vec3 aPosition;
layout(location=1) in vec3 aNormal;
layout(location=2) in vec4 aColor;
layout(location=3) in float aAlpha;
layout(location=4) in vec3 aUvMat;
uniform mat4 uViewProjection;
uniform mat4 uModel;
uniform mat4 uNormalMatrix;
out vec4 vColor;
out vec3 vNormal;
void main(){
  vColor=vec4(aColor.rgb,aAlpha);
  vNormal=mat3(uNormalMatrix)*aNormal;
  gl_Position=uViewProjection*uModel*vec4(aPosition,1.0);
}
''';

const String safeWorldFragSrc = '''
#version 300 es
precision highp float;
in vec4 vColor;
in vec3 vNormal;
uniform vec3 uLightDir;
uniform vec3 uAmbientColor;
uniform float uAmbientIntensity;
out vec4 oColor;
void main(){
  vec3 n=normalize(vNormal);
  float ndotl=max(dot(n,normalize(uLightDir)),0.0);
  vec3 lit=vColor.rgb*clamp(uAmbientColor*uAmbientIntensity+vec3(ndotl),0.0,1.0);
  oColor=vec4(lit,vColor.a);
}
''';

const String texturedWorldVertSrc = '''
#version 300 es
layout(location=0) in vec3 aPosition;
layout(location=1) in vec3 aNormal;
layout(location=2) in vec4 aColor;
layout(location=3) in float aAlpha;
layout(location=4) in vec3 aUvMat;
uniform mat4 uViewProjection;
uniform mat4 uModel;
uniform mat4 uNormalMatrix;
out vec4 vColor;
out vec3 vNormal;
out vec2 vUv;
void main(){
  vColor=vec4(aColor.rgb,aAlpha);
  vNormal=mat3(uNormalMatrix)*aNormal;
  vUv=aUvMat.xy;
  gl_Position=uViewProjection*uModel*vec4(aPosition,1.0);
}
''';

const String texturedWorldFragSrc = '''
#version 300 es
precision highp float;
in vec4 vColor;
in vec3 vNormal;
in vec2 vUv;
uniform sampler2D uAlbedo;
uniform vec3 uLightDir;
uniform vec3 uAmbientColor;
uniform float uAmbientIntensity;
out vec4 oColor;
void main(){
  vec3 n=normalize(vNormal);
  float ndotl=max(dot(n,normalize(uLightDir)),0.0);
  vec4 tex=texture(uAlbedo,vUv);
  vec3 lit=vColor.rgb*tex.rgb*clamp(uAmbientColor*uAmbientIntensity+vec3(ndotl),0.0,1.0);
  oColor=vec4(lit,vColor.a*tex.a);
}
''';

const String shadowCasterVertSrc = '''
#version 300 es
layout(location=0) in vec3 aPosition;
layout(location=4) in vec3 aUvMat;
uniform mat4 uLightViewProjection;
uniform mat4 uModel;
out highp vec2 vUv;
// No affine premultiply here, unlike depth_prepass.vert. Affine sampling is
// an artifact of *this camera's* screen-space rasterization; the shadow map
// rasterizes the same triangle from the light, where the equivalent warp
// would be a different, unrelated distortion. A masked surface therefore
// cuts its shadow from the perspective-correct UVs — the geometrically
// right holes — while the camera passes cut theirs from whatever the PS1
// profile asked for. That divergence is deliberate: the two rasterizations
// have no shared screen space to agree in.
void main(){
  vUv=aUvMat.xy;
  gl_Position=uLightViewProjection*uModel*vec4(aPosition,1.0);
}
''';

const String shadowCasterFragSrc = '''
#version 300 es
precision highp float;
in highp vec2 vUv;
uniform sampler2D uAlbedo;
uniform float uAlphaCutoff;
// §6.2: "alpha-masked geometry participates in shadow, prepass, and opaque
// depth-writing routes." Without this discard a lattice, a leaf or a grille
// casts the solid shadow of its bounding quad — the single most obvious way
// a masked material reads as fake. uAlphaCutoff==0 skips the fetch, so
// every opaque caster costs exactly what it did before this existed.
void main(){
  if(uAlphaCutoff>0.&&texture(uAlbedo,vUv).a<uAlphaCutoff)discard;
}
''';

const String shadowedWorldVertSrc = '''
#version 300 es
layout(location=0) in vec3 aPosition;
layout(location=1) in vec3 aNormal;
layout(location=2) in vec4 aColor;
layout(location=3) in float aAlpha;
layout(location=4) in vec3 aUvMat;
uniform mat4 uViewProjection;
uniform mat4 uView;
uniform mat4 uModel;
uniform mat4 uNormalMatrix;
uniform mat4 uLightViewProjection;
uniform float uVertexSnapGrid;
uniform float uAffineWarpStrength;
out vec4 vColor;
out vec3 vNormal;
out highp vec2 vUv;
out highp float vUvW;
out vec4 vLightSpacePos;
out vec3 vWorldPos;
out float vViewDepth;
void main(){
  vColor=vec4(aColor.rgb,aAlpha);
  vNormal=mat3(uNormalMatrix)*aNormal;
  vec4 worldPos=uModel*vec4(aPosition,1.0);
  vWorldPos=worldPos.xyz;
  vLightSpacePos=uLightViewProjection*worldPos;
  // RV-09 rung 5's fog: the same "linear view depth" convention SSAO/DOF
  // already reconstruct from a depth texture, computed directly here
  // instead — this pass rasterizes the actual geometry, so there is a true
  // view-space Z per-vertex already, with no texture round-trip needed.
  vViewDepth=-(uView*worldPos).z;
  vec4 clip=uViewProjection*worldPos;
  // RV-09 rung 3's PS1 profile: snaps clip-space xy to a fixed grid before
  // the perspective divide, emulating the fixed-point vertex transform
  // precision loss that gives PS1 geometry its characteristic wobble as it
  // moves. uVertexSnapGrid==0 skips the branch entirely, so the default/
  // safe path is bit-for-bit unchanged from before this rung.
  if(uVertexSnapGrid>0.0){
    vec2 ndc=clip.xy/clip.w;
    ndc=floor(ndc/uVertexSnapGrid+0.5)*uVertexSnapGrid;
    clip.xy=ndc*clip.w;
  }
  gl_Position=clip;
  // Affine UV, the PS1 rung's deferred half. GLSL ES 300 has no
  // `noperspective` qualifier, so the divide the rasterizer already performs
  // is cancelled instead of disabled: hardware hands the fragment
  // interp(v/w)/interp(1/w), so premultiplying a varying by w makes that
  // expression collapse to interp(v) — screen-space linear, which *is*
  // affine. Both varyings are scaled by the same factor so the fragment's
  // vUv/vUvW recovers exactly that, and the intermediate blend between the
  // two regimes stays continuous rather than popping at any strength.
  // uAffineWarpStrength==0 gives affineW==1.0 exactly, leaving vUv equal to
  // aUvMat.xy bit-for-bit; the fragment then skips the divide entirely on
  // the same uniform, so the perspective-correct path is untouched rather
  // than merely round-tripped. Snapping above only rewrites clip.xy, never
  // clip.w, so the two PS1 halves are independent.
  float affineW=mix(1.0,clip.w,uAffineWarpStrength);
  vUv=aUvMat.xy*affineW;
  vUvW=affineW;
}
''';

const String shadowedWorldFragSrc = '''
#version 300 es
precision highp float;
in vec4 vColor;
in vec3 vNormal;
in highp vec2 vUv;
in highp float vUvW;
in vec4 vLightSpacePos;
in vec3 vWorldPos;
in float vViewDepth;
uniform sampler2D uAlbedo;
uniform sampler2D uShadowMap;
uniform vec3 uLightPosition;
uniform vec3 uLightDirection;
uniform float uLightRange;
uniform float uLightInnerCos;
uniform float uLightOuterCos;
uniform vec3 uAmbientColor;
uniform float uAmbientIntensity;
uniform vec2 uShadowMapTexelSize;
uniform vec3 uMaterialTint;
uniform sampler2D uSsao;
uniform vec2 uSceneColorSize;
uniform float uEmissiveStrength;
uniform float uAffineWarpStrength;
uniform float uAlphaCutoff;
uniform float uOpaqueCoverage;
uniform vec3 uFogColor;
uniform float uFogStart;
uniform float uFogEnd;
uniform float uFogHeightFalloff;
uniform float uFogDensity;
layout(location=0)out vec4 oColor;
layout(location=1)out vec4 oGlow;

// Distance falloff (smooth to zero at uLightRange, matching SpotLight.range
// rather than an unbounded inverse-square that never reaches zero) times
// cone-edge falloff (smoothstep between the outer and inner cone angles,
  // SpotLight.outerConeRadians/innerConeRadians — both fields existed on the
  // API already but nothing read them before this, so the light previously
  // had a hard-edged, non-attenuating cone that read as flat/harsh instead of
// a graduated pool of light).
float lightAttenuation(vec3 worldPos){
  vec3 toFrag=worldPos-uLightPosition;
  float dist=length(toFrag);
  float distFalloff=clamp(1.-dist/uLightRange,0.,1.);
  distFalloff*=distFalloff;
  float cosAngle=dot(normalize(toFrag),normalize(uLightDirection));
  float coneFalloff=smoothstep(uLightOuterCos,uLightInnerCos,cosAngle);
  return distFalloff*coneFalloff;
}

float sampleShadow(vec3 projCoord,float bias){
  float shadowDepth=texture(uShadowMap,projCoord.xy).r;
  return projCoord.z-bias>shadowDepth?0.:1.;
}

// §8.5's fog: "distance plus restrained height/damp modulation" — the base
// term is a smoothstepped distance ramp (uFogStart..uFogEnd), not a plain
// linear one: a linear ramp's density right at uFogStart is already
// visibly nonzero, which reads as a hard onset band across a large
// continuous surface like the ground plane. smoothstep's derivative is
// zero at both ends, so density stays low just past uFogStart and eases
// in gradually instead. Height falloff and density are each optional in
// FrameEnvironment (nullable there, 0.0 here) and each written so 0.0 is
// an exact no-op, rather than needing a separate enabled flag per term:
//   - height: exp(-0*y) == 1, an identity multiply, when no falloff is set;
//   - density: 1-exp(-0*depth) == 0, so max(distance, 0) leaves the plain
//     distance term untouched when no density is set. Density can only
//     ever push fog stronger than the base distance ramp, never weaker —
//     "restrained" in the sense that it augments, never overrides.
float fogFactor(float viewDepth,float worldY){
  float distFactor=smoothstep(uFogStart,uFogEnd,viewDepth);
  float densityFactor=1.-exp(-uFogDensity*viewDepth);
  float factor=max(distFactor,densityFactor);
  float heightFactor=exp(-uFogHeightFalloff*max(worldY,0.));
  return clamp(factor*heightFactor,0.,1.);
}

float shadowFactor(float ndotl){
  vec3 projCoord=vLightSpacePos.xyz/vLightSpacePos.w;
  projCoord=projCoord*.5+.5;
  if(projCoord.x<0.||projCoord.x>1.||projCoord.y<0.||projCoord.y>1.||projCoord.z>1.){
    return 1.;
  }
  float bias=max(.004*(1.-ndotl),.0015);
  float sum=0.;
  sum+=sampleShadow(projCoord+vec3(-.5,-.5,0.)*vec3(uShadowMapTexelSize,0.),bias);
  sum+=sampleShadow(projCoord+vec3(.5,-.5,0.)*vec3(uShadowMapTexelSize,0.),bias);
  sum+=sampleShadow(projCoord+vec3(-.5,.5,0.)*vec3(uShadowMapTexelSize,0.),bias);
  sum+=sampleShadow(projCoord+vec3(.5,.5,0.)*vec3(uShadowMapTexelSize,0.),bias);
  return sum*.25;
}

void main(){
  // The divide that undoes the rasterizer's own perspective correction (see
  // shadowed_world.vert). Branched on the uniform rather than always
  // dividing, so a zero-strength draw samples the untouched vUv and is
  // bit-identical to the pre-affine path — the divisor is 1.0 there, but
  // only after an interpolate/divide round-trip that need not return
  // exactly 1.0. The branch is uniform across the whole draw, so it costs
  // no divergence.
  vec2 uv=uAffineWarpStrength>0.?vUv/vUvW:vUv;
  vec4 tex=texture(uAlbedo,uv);
  // §6.2's alpha-masked route. Deliberately the first thing after the
  // fetch it depends on, and ahead of all the lighting below: a discarded
  // fragment must not pay for four shadow-map taps and two normalizes it
  // will never use. uAlphaCutoff==0 is the pass's "this material has no
  // cutout" sentinel (MaterialDefinition.validate forbids a real zero), so
  // opaque and blended draws take a path containing no alpha compare at
  // all rather than one comparing against an unreachable threshold. The
  // same test, against the same uv, runs in depth_prepass.frag and
  // shadow_caster.frag — three passes must agree on which fragments exist
  // or SSAO, DOF and shadowing all occlude against holes this pass shaded
  // through.
  if(uAlphaCutoff>0.&&tex.a<uAlphaCutoff)discard;
  vec3 n=normalize(vNormal);
  vec3 toLight=normalize(uLightPosition-vWorldPos);
  float ndotl=max(dot(n,toLight),0.);
  float shadow=shadowFactor(ndotl);
  float attenuation=lightAttenuation(vWorldPos);
  // §8.5: "modulates ambient only" — SSAO must never darken the direct
  // (N.L * shadow * attenuation) term, only the ambient fill, or it would
  // double up with real shadowing and read as an incorrect global darkening
  // rather than contact occlusion specifically.
  vec2 screenUv=gl_FragCoord.xy/uSceneColorSize;
  float ao=texture(uSsao,screenUv).r;
  vec3 ambient=uAmbientColor*uAmbientIntensity*ao;
  vec3 lit=vColor.rgb*tex.rgb*uMaterialTint*clamp(ambient+vec3(ndotl*shadow*attenuation),0.,1.);
  // Fog blends the surface's own lit color toward uFogColor only — never
  // oGlow below, which stays a declared emissive quantity independent of
  // how much atmosphere sits between the surface and the camera, matching
  // §8.7's "does not infer glow from final luma" scoping: fog is a
  // property of oColor's reflected/lit light, not of emission.
  float fog=fogFactor(vViewDepth,vWorldPos.y);
  vec3 foggedLit=mix(lit,uFogColor,fog);
  // Bug 18: vColor.a*tex.a is the correct alpha for a blended draw and the
  // wrong one for everything else. present.frag copies this channel
  // straight through to a canvas created with the default alpha:true, so an
  // opaque or masked surface that emitted a texel's own alpha would show
  // the *page* through solid geometry. Coverage, not transparency, is what
  // an opaque or masked fragment writes: whatever survived the discard
  // above is fully covering, and an opaque draw always was. uOpaqueCoverage
  // is exactly 0 or 1, so the mix is exact in both directions and the
  // blended path keeps its pre-existing expression bit-for-bit.
  float outAlpha=mix(vColor.a*tex.a,1.,uOpaqueCoverage);
  oColor=vec4(foggedLit,outAlpha);
  // §8.7: bloom reads this declared attachment directly, never inferring
  // glow from oColor's final luma — a bright-but-non-emissive lit surface
  // (e.g. the checkerboard floor under strong light) must never bloom, only
  // a material with real emissiveStrength does, independent of how the
  // surface happens to be lit this frame.
  oGlow=vec4(uMaterialTint*uEmissiveStrength,1.);
}
''';

const String presentVertSrc = '''
#version 300 es
out vec2 vUv;
void main(){
  vec2 p=vec2(float((gl_VertexID<<1)&2),float(gl_VertexID&2));
  vUv=p;
  gl_Position=vec4(p*2.0-1.0,0.0,1.0);
}
''';

const String presentFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uTex;
out vec4 oColor;
void main(){
  oColor=texture(uTex,vUv);
}
''';

const String depthPrepassVertSrc = '''
#version 300 es
layout(location=0) in vec3 aPosition;
layout(location=4) in vec3 aUvMat;
uniform mat4 uViewProjection;
uniform mat4 uModel;
uniform float uVertexSnapGrid;
uniform float uAffineWarpStrength;
out highp vec2 vUv;
out highp float vUvW;
// This prepass must land geometry on exactly the same pixels shadowedWorld
// will, because its depth is what SSAO occludes against and what
// shadowedWorld then samples back at its *own* gl_FragCoord. Snapping there
// and not here would mean the AO texel a fragment reads was computed for a
// slightly different surface than the one being shaded, and the error grows
// with the grid. The snap math below is deliberately identical to
// shadowed_world.vert's, including uVertexSnapGrid==0 skipping the branch.
// The same reasoning now covers UVs: an alpha-masked surface's holes must
// land on the same pixels in both passes, and affine sampling moves where a
// given texel lands, so the w-premultiply below is the same expression
// shadowed_world.vert uses and is driven from the same per-material weight.
void main(){
  vec4 clip=uViewProjection*uModel*vec4(aPosition,1.0);
  if(uVertexSnapGrid>0.0){
    vec2 ndc=clip.xy/clip.w;
    ndc=floor(ndc/uVertexSnapGrid+0.5)*uVertexSnapGrid;
    clip.xy=ndc*clip.w;
  }
  gl_Position=clip;
  float affineW=mix(1.0,clip.w,uAffineWarpStrength);
  vUv=aUvMat.xy*affineW;
  vUvW=affineW;
}
''';

const String depthPrepassFragSrc = '''
#version 300 es
precision highp float;
in highp vec2 vUv;
in highp float vUvW;
uniform sampler2D uAlbedo;
uniform float uAlphaCutoff;
uniform float uAffineWarpStrength;
// §6.2: "includes opaque + alpha-masked depth." A masked surface's holes
// must not write depth, or SSAO occludes against geometry the world pass
// discarded and DOF's CoC defocuses against a surface nothing shaded. The
// compare is bit-identical to shadowed_world.frag's — same uv recovery,
// same threshold, same direction — because any divergence reintroduces
// exactly the class of bug the vertex-snap parity fix (bug 17) closed.
// Everything is inside the uAlphaCutoff>0. branch, so an unmasked draw
// costs no texture fetch at all here, only the interpolation the varyings
// were already going to do.
void main(){
  if(uAlphaCutoff>0.){
    vec2 uv=uAffineWarpStrength>0.?vUv/vUvW:vUv;
    if(texture(uAlbedo,uv).a<uAlphaCutoff)discard;
  }
}
''';

const String depthDebugFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uSceneDepth;
uniform float uNear;
uniform float uFar;
uniform float uDisplayRange;
out vec4 oColor;
void main(){
  float raw=texture(uSceneDepth,vUv).r;
  float ndc=raw*2.0-1.0;
  float linear=(2.0*uNear*uFar)/(uFar+uNear-ndc*(uFar-uNear));
  // uFar is the camera's real projection far plane (100, for correct depth
  // reconstruction above) — normalizing display shade against it directly
  // would crush every visible surface (a handful of units away) into a
  // sliver near 0.0, indistinguishable from black, while the empty
  // background (which clears to exactly uFar) reads pure white. uDisplayRange
  // is a separate, much smaller distance chosen to match this scene's
  // actual scale, so nearby geometry spans a real visible gradient instead
  // of a hard silhouette.
  float shade=clamp(linear/uDisplayRange,0.0,1.0);
  oColor=vec4(vec3(shade),1.0);
}
''';

const String ssaoOcclusionFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uSceneDepth;
uniform float uNear;
uniform float uFar;
uniform float uProjScaleX;
uniform float uProjScaleY;
uniform float uRadius;
uniform float uStrength;
out vec4 oColor;

const int KERNEL_SIZE=8;
const vec3 KERNEL[8]=vec3[8](
  vec3( 0.35, 0.23, 0.45),
  vec3(-0.28, 0.41, 0.32),
  vec3( 0.18,-0.36, 0.55),
  vec3(-0.42,-0.19, 0.28),
  vec3( 0.51, 0.08, 0.18),
  vec3(-0.11, 0.53, 0.16),
  vec3( 0.07,-0.48, 0.38),
  vec3(-0.33,-0.31, 0.48)
);

float linearDepth(float raw){
  float ndc=raw*2.0-1.0;
  return (2.0*uNear*uFar)/(uFar+uNear-ndc*(uFar-uNear));
}

vec3 viewPosAt(vec2 uv){
  float viewZ=-linearDepth(texture(uSceneDepth,uv).r);
  vec2 ndc=uv*2.0-1.0;
  float viewX=ndc.x*(-viewZ)/uProjScaleX;
  float viewY=ndc.y*(-viewZ)/uProjScaleY;
  return vec3(viewX,viewY,viewZ);
}

// Pinned per-pixel kernel rotation — a deterministic hash of screen
// position, not per-frame randomness, matching §8.5's "rotates a small
// kernel from pinned blue noise" without the extra machinery of an actual
// noise texture: the rotation angle is stable across frames for a given
// pixel, which is what "pinned" requires (temporal stability), while still
// varying spatially enough to break up banding between neighboring samples.
float pinnedRotation(vec2 fragCoord){
  return fract(sin(dot(fragCoord,vec2(12.9898,78.233)))*43758.5453)*6.2831853;
}

void main(){
  vec3 originView=viewPosAt(vUv);
  // Screen-space derivatives reconstruct a per-fragment normal from
  // neighboring depth samples alone — no G-buffer normal attachment exists
  // (deferred; see depth_prepass.dart's doc comment), which is sufficient
  // for a chunky/stylized AO term rather than a precision-critical one.
  vec3 normalView=normalize(cross(dFdx(originView),dFdy(originView)));

  // Rotates each kernel sample's tangent-plane (x,y) offset in place, before
  // it's transformed into view space by tbn below — this is what actually
  // varies the kernel per pixel; rotating the already-reprojected screen UV
  // afterward would rotate around the wrong origin and misalign every
  // sample from the surface it's meant to test.
  float angle=pinnedRotation(gl_FragCoord.xy);
  float ca=cos(angle);
  float sa=sin(angle);
  mat2 rot=mat2(ca,sa,-sa,ca);

  vec3 up=abs(normalView.z)<0.99?vec3(0.0,0.0,1.0):vec3(1.0,0.0,0.0);
  vec3 tangent=normalize(cross(up,normalView));
  vec3 bitangent=cross(normalView,tangent);
  mat3 tbn=mat3(tangent,bitangent,normalView);

  float occlusion=0.0;
  for(int i=0;i<KERNEL_SIZE;i++){
    vec3 kernelSample=KERNEL[i];
    kernelSample.xy=rot*kernelSample.xy;
    vec3 samplePos=originView+tbn*kernelSample*uRadius;
    // Project the sample's view-space position back to screen UV using the
    // same scale factors used to reconstruct it, inverted.
    vec2 sampleUv=vec2(
      samplePos.x*uProjScaleX/(-samplePos.z),
      samplePos.y*uProjScaleY/(-samplePos.z)
    );
    // NDC [-1,1] -> UV [0,1] requires the constant 0.5, not vUv (the
    // *current* fragment's own UV) — adding vUv here was a real bug: it
    // conflated "this sample's own absolute reprojected screen position"
    // with "an offset relative to the current fragment," producing an
    // error of (vUv-0.5) per axis that grows with distance from screen
    // center. That's exactly what produced a huge, blobby, non-local dark
    // region instead of contact occlusion — every sample tested a wildly
    // wrong depth location except right at screen center, where the error
    // happened to be near zero.
    sampleUv=sampleUv*0.5+0.5;
    if(sampleUv.x<0.0||sampleUv.x>1.0||sampleUv.y<0.0||sampleUv.y>1.0){
      continue;
    }
    vec3 occluderView=viewPosAt(sampleUv);
    float rangeCheck=smoothstep(0.0,1.0,uRadius/max(abs(originView.z-occluderView.z),0.0001));
    occlusion+=(occluderView.z>=samplePos.z+0.02?1.0:0.0)*rangeCheck;
  }
  float ao=1.0-clamp((occlusion/float(KERNEL_SIZE))*uStrength,0.0,1.0);
  oColor=vec4(vec3(ao),1.0);
}
''';

const String ssaoBlurFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uSsaoRaw;
uniform sampler2D uSceneDepth;
uniform vec2 uTexelSize;
uniform float uNear;
uniform float uFar;
out vec4 oColor;

float linearDepth(float raw){
  float ndc=raw*2.0-1.0;
  return (2.0*uNear*uFar)/(uFar+uNear-ndc*(uFar-uNear));
}

// §8.5: "uses a depth-aware bilateral blur rather than smearing across
// silhouettes" — a plain box blur would bleed occlusion from a near object
// onto a far background behind it (or vice versa) whenever they share
// screen-space pixels near a silhouette edge; weighting each tap by how
// close its depth is to the center tap's depth is what keeps the blur
// confined to one surface at a time.
void main(){
  float centerDepth=linearDepth(texture(uSceneDepth,vUv).r);
  float sum=0.0;
  float weightSum=0.0;
  for(int y=-2;y<=2;y++){
    for(int x=-2;x<=2;x++){
      vec2 offset=vec2(float(x),float(y))*uTexelSize;
      vec2 sampleUv=vUv+offset;
      float sampleDepth=linearDepth(texture(uSceneDepth,sampleUv).r);
      float depthWeight=1.0/(1.0+abs(sampleDepth-centerDepth)*4.0);
      sum+=texture(uSsaoRaw,sampleUv).r*depthWeight;
      weightSum+=depthWeight;
    }
  }
  float blurred=sum/max(weightSum,0.0001);
  oColor=vec4(vec3(blurred),1.0);
}
''';

const String bloomBlurFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uSource;
uniform vec2 uTexelStep;
out vec4 oColor;

const float WEIGHTS[5]=float[5](0.227027,0.1945946,0.1216216,0.054054,0.016216);

void main(){
  vec3 sum=texture(uSource,vUv).rgb*WEIGHTS[0];
  for(int i=1;i<5;i++){
    vec2 offset=uTexelStep*float(i);
    sum+=texture(uSource,vUv+offset).rgb*WEIGHTS[i];
    sum+=texture(uSource,vUv-offset).rgb*WEIGHTS[i];
  }
  oColor=vec4(sum,1.0);
}
''';

const String bloomCompositeFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uBloom;
uniform float uBloomStrength;
out vec4 oColor;

void main(){
  oColor=vec4(texture(uBloom,vUv).rgb*uBloomStrength,1.0);
}
''';

const String dofCompositeFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uSharp;
uniform sampler2D uBlurred;
uniform sampler2D uSceneDepth;
uniform float uNear;
uniform float uFar;
uniform float uFocusDistance;
uniform float uFocusRange;
uniform float uStrength;
out vec4 oColor;

float linearDepth(float raw){
  float ndc=raw*2.0-1.0;
  return (2.0*uNear*uFar)/(uFar+uNear-ndc*(uFar-uNear));
}

// Circle-of-confusion is a simple linear ramp from the focus distance
// outward (front and back treated the same — no separate near/far falloff
// curve), clamped to [0,1] and scaled by uStrength so
// PostProcessState.depthOfFieldStrength == 0 is a true no-op (coc == 0
// everywhere, oColor == the sharp source exactly).
void main(){
  float depth=linearDepth(texture(uSceneDepth,vUv).r);
  float coc=clamp(abs(depth-uFocusDistance)/max(uFocusRange,0.0001),0.0,1.0)*uStrength;
  vec3 sharp=texture(uSharp,vUv).rgb;
  vec3 blurred=texture(uBlurred,vUv).rgb;
  oColor=vec4(mix(sharp,blurred,coc),1.0);
}
''';

const String gradeLutFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uScene;
uniform sampler2D uLut;
uniform float uLutSize;
uniform float uStrength;
out vec4 oColor;

// §5.3's "identity LUT" baseline resource and this shader's actual grade LUT
// are both just textures in this same unwrapped-3D-LUT layout (width =
// size*size, height = size, blue index selects a size*size horizontal
// slice) — there is nothing identity-specific about the sampling path
// itself, only about what a given LUT texture's texels happen to encode.
vec3 sampleLut(vec3 color){
  float size=uLutSize;
  float maxIndex=size-1.0;
  vec3 scaled=clamp(color,0.0,1.0)*maxIndex;
  float bLow=floor(scaled.b);
  float bHigh=min(bLow+1.0,maxIndex);
  float bFrac=scaled.b-bLow;
  vec2 texel=vec2(1.0/(size*size),1.0/size);
  vec2 rg=vec2(scaled.r+0.5,scaled.g+0.5);
  vec2 uvLow=vec2((bLow*size+rg.x)*texel.x,rg.y*texel.y);
  vec2 uvHigh=vec2((bHigh*size+rg.x)*texel.x,rg.y*texel.y);
  vec3 colorLow=texture(uLut,uvLow).rgb;
  vec3 colorHigh=texture(uLut,uvHigh).rgb;
  return mix(colorLow,colorHigh,bFrac);
}

void main(){
  vec3 scene=texture(uScene,vUv).rgb;
  vec3 graded=sampleLut(scene);
  oColor=vec4(mix(scene,graded,uStrength),1.0);
}
''';

const String ps1QuantizeFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uScene;
uniform float uQuantizationBits;
uniform float uDitherStrength;
out vec4 oColor;

const float BAYER4X4[16]=float[16](
  0.0,8.0,2.0,10.0,
  12.0,4.0,14.0,6.0,
  3.0,11.0,1.0,9.0,
  15.0,7.0,13.0,5.0
);

float bayerValue(vec2 fragCoord){
  int x=int(mod(fragCoord.x,4.0));
  int y=int(mod(fragCoord.y,4.0));
  return BAYER4X4[y*4+x]/16.0;
}

// §6.2's "quantization/dither is an explicit composite after LUT grade":
// an ordered (Bayer 4x4) dither offset, scaled to one quantization step, is
// added before rounding to uQuantizationBits levels per channel — this is
// what breaks a hard quantization boundary into a dithered gradient instead
// of a flat color band. uQuantizationBits==8 (RGBA8's own native precision)
// with uDitherStrength==0 round-trips the source exactly: no dither offset
// is added, and floor(x*255+0.5)/255 returns an already-8-bit value
// unchanged.
void main(){
  vec3 scene=texture(uScene,vUv).rgb;
  float levels=pow(2.0,uQuantizationBits)-1.0;
  float dither=(bayerValue(gl_FragCoord.xy)-0.5)*uDitherStrength/levels;
  vec3 dithered=clamp(scene+dither,0.0,1.0);
  vec3 quantized=floor(dithered*levels+0.5)/levels;
  oColor=vec4(quantized,1.0);
}
''';

const String vhsFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uScene;
uniform sampler2D uHistory;
uniform float uTime;
uniform float uChromaWeight;
uniform float uTrackingWeight;
uniform float uNoiseWeight;
uniform float uHeadSwitchWeight;
uniform float uDropoutWeight;
uniform float uGhostWeight;
out vec4 oColor;

float hash(vec2 p){
  return fract(sin(dot(p,vec2(12.9898,78.233)))*43758.5453);
}

// §8.10: "sample the jittered/tracking UV before YIQ/chroma work so later
// sampling does not overwrite earlier effects" — tracking jitter is
// computed and applied to the UV exactly once, up front; every later
// effect either operates on the resulting single sample or samples a
// further offset FROM that same jittered UV, never re-reading uScene at
// the original vUv.
void main(){
  float scanline=vUv.y;

  // Tracking: a per-scanline horizontal jitter, re-rolled roughly 8 times
  // a second (not per-frame) so it reads as tape wobble rather than
  // high-frequency noise. Comfort clamp: 0.02 UV (a few source texels at
  // this bootstrap's 384-wide internal resolution) is the max displacement
  // regardless of weight — a weight of 1.0 must read as "visibly glitchy,"
  // never as "the image is unreadable."
  float trackingNoise=hash(vec2(floor(scanline*216.0),floor(uTime*8.0)))-0.5;
  float jitter=trackingNoise*0.02*uTrackingWeight;
  vec2 uv=vec2(clamp(vUv.x+jitter,0.0,1.0),vUv.y);
  vec3 raw=texture(uScene,uv).rgb;

  // Chroma bleed: convert to YIQ, sample a second, further-offset UV for
  // the chroma (I/Q) channels only — luma (what reads as "sharp" to the
  // eye) stays exactly where tracking already put it; only color smears.
  vec2 chromaUv=vec2(clamp(uv.x+0.01*uChromaWeight,0.0,1.0),uv.y);
  vec3 rawChroma=texture(uScene,chromaUv).rgb;
  float y=dot(raw,vec3(0.299,0.587,0.114));
  float i=dot(rawChroma,vec3(0.596,-0.274,-0.322));
  float q=dot(rawChroma,vec3(0.211,-0.523,0.312));
  vec3 yiqColor=vec3(
    y+0.956*i+0.621*q,
    y-0.272*i-0.647*q,
    y-1.106*i+1.703*q
  );
  vec3 color=mix(raw,yiqColor,uChromaWeight);

  // Static/snow: modeled in YIQ (luma + chroma), the same conversion
  // chroma bleed already uses above, not independent RGB — real analog
  // colour noise comes from the chroma subcarrier, so its hues are
  // correlated/limited rather than arbitrary per-channel static. Noise
  // cells are quantized coarser along x than y, giving each speckle a
  // short horizontal dash instead of an isolated dot — a "vague line
  // shape," matching how scanline-based static actually streaks. A
  // sparser, stronger sparkle layer and a rare single-sample micro-
  // distortion (an actual tiny position offset, not just colour) are both
  // gated by a high-threshold mask so only occasional pixels carry the
  // effect — small magnitude on top of that sparsity, for a sprinkle, not
  // a wash.
  vec2 noiseCell=vec2(floor(gl_FragCoord.x/3.0),gl_FragCoord.y)+uTime*60.0;
  float noiseY=(hash(noiseCell)-0.5)*0.05;
  float noiseI=(hash(noiseCell+vec2(17.0,3.0))-0.5)*0.14;
  float noiseQ=(hash(noiseCell+vec2(53.0,29.0))-0.5)*0.14;
  vec3 noiseYiq=vec3(
    noiseY+0.956*noiseI+0.621*noiseQ,
    noiseY-0.272*noiseI-0.647*noiseQ,
    noiseY-1.106*noiseI+1.703*noiseQ
  );
  color+=noiseYiq*uNoiseWeight;
  float sparkleMask=step(0.995,hash(noiseCell+vec2(97.0,3.0)));
  float sparkleI=(hash(noiseCell+5.0)-0.5)*2.0;
  float sparkleQ=(hash(noiseCell+9.0)-0.5)*2.0;
  vec3 sparkleYiq=0.5+0.5*vec3(
    0.956*sparkleI+0.621*sparkleQ,
    -0.272*sparkleI-0.647*sparkleQ,
    -1.106*sparkleI+1.703*sparkleQ
  );
  color+=sparkleYiq*sparkleMask*0.3*uNoiseWeight;
  float distortMask=step(0.997,hash(noiseCell+vec2(43.0,61.0)));
  vec2 distortOffset=
    vec2(hash(noiseCell+1.0)-0.5,hash(noiseCell+2.0)-0.5)*0.01;
  vec3 distortColor=texture(uScene,clamp(uv+distortOffset,0.0,1.0)).rgb;
  color=mix(color,distortColor,distortMask*0.5*uNoiseWeight);

  // Head-switch band: a thin strip near the bottom of frame (where a real
  // VCR's playback head crosses the tape edge) gets a stronger tear,
  // fading smoothly over the band's height rather than a hard cutoff.
  float headSwitchBand=smoothstep(0.06,0.0,abs(scanline-0.98));
  float headSwitchJitter=(hash(vec2(uTime*30.0,scanline))-0.5)*0.06;
  vec2 headSwitchUv=vec2(
    clamp(uv.x+headSwitchJitter*uHeadSwitchWeight*headSwitchBand,0.0,1.0),
    uv.y
  );
  vec3 headSwitchColor=texture(uScene,headSwitchUv).rgb;
  color=mix(color,headSwitchColor,uHeadSwitchWeight*headSwitchBand);

  // Dropout: sparse, per-scanline streaks mimicking analog tape dropout.
  // Real dropout is neither a flat full-width bar nor a fixed brightness —
  // a per-x noise mask (smoothstepped, not a hard cutoff) makes each
  // streak's width and edges vary along its length, and a per-streak
  // random intensity keeps consecutive dropouts from looking identical. A
  // slow ~6Hz reroll (not per-frame) and a high activation threshold keep
  // this an occasional glitch rather than a strobe — subtle enough not to
  // distract during continuous play, even at uDropoutWeight's full value.
  float dropoutCell=floor(uTime*6.0);
  float dropoutRoll=hash(vec2(floor(scanline*216.0),dropoutCell));
  float dropoutActive=step(0.994,dropoutRoll);
  float dropoutIntensity=hash(vec2(dropoutCell,17.0))*0.5+0.4;
  float dropoutMask=hash(
    vec2(floor(uv.x*48.0),floor(scanline*216.0)+dropoutCell*3.0)
  );
  float dropoutStripe=
    dropoutActive*uDropoutWeight*smoothstep(0.3,0.9,dropoutMask);
  color=mix(color,vec3(dropoutIntensity),dropoutStripe*0.8);

  // Ghosting: blends in last frame's own VHS *output* (uHistory, never
  // uScene), horizontally offset, for a trailing double-image echo —
  // reading the previous frame's already-composited result is what makes
  // this a genuine feedback trail rather than a static double-exposure.
  vec2 ghostUv=vec2(clamp(uv.x-0.015,0.0,1.0),uv.y);
  vec3 ghostColor=texture(uHistory,ghostUv).rgb;
  color=mix(color,ghostColor,uGhostWeight*0.5);

  oColor=vec4(clamp(color,0.0,1.0),1.0);
}
''';
